INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'05',N'05001',N'ANTIOQUIA',N'MEDELLÍN',N'Municipio'),
	 (N'05',N'05002',N'ANTIOQUIA',N'ABEJORRAL',N'Municipio'),
	 (N'05',N'05004',N'ANTIOQUIA',N'ABRIAQUÍ',N'Municipio'),
	 (N'05',N'05021',N'ANTIOQUIA',N'ALEJANDRÍA',N'Municipio'),
	 (N'05',N'05030',N'ANTIOQUIA',N'AMAGÁ',N'Municipio'),
	 (N'05',N'05031',N'ANTIOQUIA',N'AMALFI',N'Municipio'),
	 (N'05',N'05034',N'ANTIOQUIA',N'ANDES',N'Municipio'),
	 (N'05',N'05036',N'ANTIOQUIA',N'ANGELÓPOLIS',N'Municipio'),
	 (N'05',N'05038',N'ANTIOQUIA',N'ANGOSTURA',N'Municipio'),
	 (N'05',N'05040',N'ANTIOQUIA',N'ANORÍ',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'05',N'05042',N'ANTIOQUIA',N'SANTA FÉ DE ANTIOQUIA',N'Municipio'),
	 (N'05',N'05044',N'ANTIOQUIA',N'ANZÁ',N'Municipio'),
	 (N'05',N'05045',N'ANTIOQUIA',N'APARTADÓ',N'Municipio'),
	 (N'05',N'05051',N'ANTIOQUIA',N'ARBOLETES',N'Municipio'),
	 (N'05',N'05055',N'ANTIOQUIA',N'ARGELIA',N'Municipio'),
	 (N'05',N'05059',N'ANTIOQUIA',N'ARMENIA',N'Municipio'),
	 (N'05',N'05079',N'ANTIOQUIA',N'BARBOSA',N'Municipio'),
	 (N'05',N'05086',N'ANTIOQUIA',N'BELMIRA',N'Municipio'),
	 (N'05',N'05088',N'ANTIOQUIA',N'BELLO',N'Municipio'),
	 (N'05',N'05091',N'ANTIOQUIA',N'BETANIA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'05',N'05093',N'ANTIOQUIA',N'BETULIA',N'Municipio'),
	 (N'05',N'05101',N'ANTIOQUIA',N'CIUDAD BOLÍVAR',N'Municipio'),
	 (N'05',N'05107',N'ANTIOQUIA',N'BRICEÑO',N'Municipio'),
	 (N'05',N'05113',N'ANTIOQUIA',N'BURITICÁ',N'Municipio'),
	 (N'05',N'05120',N'ANTIOQUIA',N'CÁCERES',N'Municipio'),
	 (N'05',N'05125',N'ANTIOQUIA',N'CAICEDO',N'Municipio'),
	 (N'05',N'05129',N'ANTIOQUIA',N'CALDAS',N'Municipio'),
	 (N'05',N'05134',N'ANTIOQUIA',N'CAMPAMENTO',N'Municipio'),
	 (N'05',N'05138',N'ANTIOQUIA',N'CAÑASGORDAS',N'Municipio'),
	 (N'05',N'05142',N'ANTIOQUIA',N'CARACOLÍ',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'05',N'05145',N'ANTIOQUIA',N'CARAMANTA',N'Municipio'),
	 (N'05',N'05147',N'ANTIOQUIA',N'CAREPA',N'Municipio'),
	 (N'05',N'05148',N'ANTIOQUIA',N'EL CARMEN DE VIBORAL',N'Municipio'),
	 (N'05',N'05150',N'ANTIOQUIA',N'CAROLINA',N'Municipio'),
	 (N'05',N'05154',N'ANTIOQUIA',N'CAUCASIA',N'Municipio'),
	 (N'05',N'05172',N'ANTIOQUIA',N'CHIGORODÓ',N'Municipio'),
	 (N'05',N'05190',N'ANTIOQUIA',N'CISNEROS',N'Municipio'),
	 (N'05',N'05197',N'ANTIOQUIA',N'COCORNÁ',N'Municipio'),
	 (N'05',N'05206',N'ANTIOQUIA',N'CONCEPCIÓN',N'Municipio'),
	 (N'05',N'05209',N'ANTIOQUIA',N'CONCORDIA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'05',N'05212',N'ANTIOQUIA',N'COPACABANA',N'Municipio'),
	 (N'05',N'05234',N'ANTIOQUIA',N'DABEIBA',N'Municipio'),
	 (N'05',N'05237',N'ANTIOQUIA',N'DONMATÍAS',N'Municipio'),
	 (N'05',N'05240',N'ANTIOQUIA',N'EBÉJICO',N'Municipio'),
	 (N'05',N'05250',N'ANTIOQUIA',N'EL BAGRE',N'Municipio'),
	 (N'05',N'05264',N'ANTIOQUIA',N'ENTRERRÍOS',N'Municipio'),
	 (N'05',N'05266',N'ANTIOQUIA',N'ENVIGADO',N'Municipio'),
	 (N'05',N'05282',N'ANTIOQUIA',N'FREDONIA',N'Municipio'),
	 (N'05',N'05284',N'ANTIOQUIA',N'FRONTINO',N'Municipio'),
	 (N'05',N'05306',N'ANTIOQUIA',N'GIRALDO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'05',N'05308',N'ANTIOQUIA',N'GIRARDOTA',N'Municipio'),
	 (N'05',N'05310',N'ANTIOQUIA',N'GÓMEZ PLATA',N'Municipio'),
	 (N'05',N'05313',N'ANTIOQUIA',N'GRANADA',N'Municipio'),
	 (N'05',N'05315',N'ANTIOQUIA',N'GUADALUPE',N'Municipio'),
	 (N'05',N'05318',N'ANTIOQUIA',N'GUARNE',N'Municipio'),
	 (N'05',N'05321',N'ANTIOQUIA',N'GUATAPÉ',N'Municipio'),
	 (N'05',N'05347',N'ANTIOQUIA',N'HELICONIA',N'Municipio'),
	 (N'05',N'05353',N'ANTIOQUIA',N'HISPANIA',N'Municipio'),
	 (N'05',N'05360',N'ANTIOQUIA',N'ITAGÜÍ',N'Municipio'),
	 (N'05',N'05361',N'ANTIOQUIA',N'ITUANGO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'05',N'05364',N'ANTIOQUIA',N'JARDÍN',N'Municipio'),
	 (N'05',N'05368',N'ANTIOQUIA',N'JERICÓ',N'Municipio'),
	 (N'05',N'05376',N'ANTIOQUIA',N'LA CEJA',N'Municipio'),
	 (N'05',N'05380',N'ANTIOQUIA',N'LA ESTRELLA',N'Municipio'),
	 (N'05',N'05390',N'ANTIOQUIA',N'LA PINTADA',N'Municipio'),
	 (N'05',N'05400',N'ANTIOQUIA',N'LA UNIÓN',N'Municipio'),
	 (N'05',N'05411',N'ANTIOQUIA',N'LIBORINA',N'Municipio'),
	 (N'05',N'05425',N'ANTIOQUIA',N'MACEO',N'Municipio'),
	 (N'05',N'05440',N'ANTIOQUIA',N'MARINILLA',N'Municipio'),
	 (N'05',N'05467',N'ANTIOQUIA',N'MONTEBELLO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'05',N'05475',N'ANTIOQUIA',N'MURINDÓ',N'Municipio'),
	 (N'05',N'05480',N'ANTIOQUIA',N'MUTATÁ',N'Municipio'),
	 (N'05',N'05483',N'ANTIOQUIA',N'NARIÑO',N'Municipio'),
	 (N'05',N'05490',N'ANTIOQUIA',N'NECOCLÍ',N'Municipio'),
	 (N'05',N'05495',N'ANTIOQUIA',N'NECHÍ',N'Municipio'),
	 (N'05',N'05501',N'ANTIOQUIA',N'OLAYA',N'Municipio'),
	 (N'05',N'05541',N'ANTIOQUIA',N'PEÑOL',N'Municipio'),
	 (N'05',N'05543',N'ANTIOQUIA',N'PEQUE',N'Municipio'),
	 (N'05',N'05576',N'ANTIOQUIA',N'PUEBLORRICO',N'Municipio'),
	 (N'05',N'05579',N'ANTIOQUIA',N'PUERTO BERRÍO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'05',N'05585',N'ANTIOQUIA',N'PUERTO NARE',N'Municipio'),
	 (N'05',N'05591',N'ANTIOQUIA',N'PUERTO TRIUNFO',N'Municipio'),
	 (N'05',N'05604',N'ANTIOQUIA',N'REMEDIOS',N'Municipio'),
	 (N'05',N'05607',N'ANTIOQUIA',N'RETIRO',N'Municipio'),
	 (N'05',N'05615',N'ANTIOQUIA',N'RIONEGRO',N'Municipio'),
	 (N'05',N'05628',N'ANTIOQUIA',N'SABANALARGA',N'Municipio'),
	 (N'05',N'05631',N'ANTIOQUIA',N'SABANETA',N'Municipio'),
	 (N'05',N'05642',N'ANTIOQUIA',N'SALGAR',N'Municipio'),
	 (N'05',N'05647',N'ANTIOQUIA',N'SAN ANDRÉS DE CUERQUÍA',N'Municipio'),
	 (N'05',N'05649',N'ANTIOQUIA',N'SAN CARLOS',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'05',N'05652',N'ANTIOQUIA',N'SAN FRANCISCO',N'Municipio'),
	 (N'05',N'05656',N'ANTIOQUIA',N'SAN JERÓNIMO',N'Municipio'),
	 (N'05',N'05658',N'ANTIOQUIA',N'SAN JOSÉ DE LA MONTAÑA',N'Municipio'),
	 (N'05',N'05659',N'ANTIOQUIA',N'SAN JUAN DE URABÁ',N'Municipio'),
	 (N'05',N'05660',N'ANTIOQUIA',N'SAN LUIS',N'Municipio'),
	 (N'05',N'05664',N'ANTIOQUIA',N'SAN PEDRO DE LOS MILAGROS',N'Municipio'),
	 (N'05',N'05665',N'ANTIOQUIA',N'SAN PEDRO DE URABÁ',N'Municipio'),
	 (N'05',N'05667',N'ANTIOQUIA',N'SAN RAFAEL',N'Municipio'),
	 (N'05',N'05670',N'ANTIOQUIA',N'SAN ROQUE',N'Municipio'),
	 (N'05',N'05674',N'ANTIOQUIA',N'SAN VICENTE FERRER',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'05',N'05679',N'ANTIOQUIA',N'SANTA BÁRBARA',N'Municipio'),
	 (N'05',N'05686',N'ANTIOQUIA',N'SANTA ROSA DE OSOS',N'Municipio'),
	 (N'05',N'05690',N'ANTIOQUIA',N'SANTO DOMINGO',N'Municipio'),
	 (N'05',N'05697',N'ANTIOQUIA',N'EL SANTUARIO',N'Municipio'),
	 (N'05',N'05736',N'ANTIOQUIA',N'SEGOVIA',N'Municipio'),
	 (N'05',N'05756',N'ANTIOQUIA',N'SONSÓN',N'Municipio'),
	 (N'05',N'05761',N'ANTIOQUIA',N'SOPETRÁN',N'Municipio'),
	 (N'05',N'05789',N'ANTIOQUIA',N'TÁMESIS',N'Municipio'),
	 (N'05',N'05790',N'ANTIOQUIA',N'TARAZÁ',N'Municipio'),
	 (N'05',N'05792',N'ANTIOQUIA',N'TARSO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'05',N'05809',N'ANTIOQUIA',N'TITIRIBÍ',N'Municipio'),
	 (N'05',N'05819',N'ANTIOQUIA',N'TOLEDO',N'Municipio'),
	 (N'05',N'05837',N'ANTIOQUIA',N'TURBO',N'Municipio'),
	 (N'05',N'05842',N'ANTIOQUIA',N'URAMITA',N'Municipio'),
	 (N'05',N'05847',N'ANTIOQUIA',N'URRAO',N'Municipio'),
	 (N'05',N'05854',N'ANTIOQUIA',N'VALDIVIA',N'Municipio'),
	 (N'05',N'05856',N'ANTIOQUIA',N'VALPARAÍSO',N'Municipio'),
	 (N'05',N'05858',N'ANTIOQUIA',N'VEGACHÍ',N'Municipio'),
	 (N'05',N'05861',N'ANTIOQUIA',N'VENECIA',N'Municipio'),
	 (N'05',N'05873',N'ANTIOQUIA',N'VIGÍA DEL FUERTE',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'05',N'05885',N'ANTIOQUIA',N'YALÍ',N'Municipio'),
	 (N'05',N'05887',N'ANTIOQUIA',N'YARUMAL',N'Municipio'),
	 (N'05',N'05890',N'ANTIOQUIA',N'YOLOMBÓ',N'Municipio'),
	 (N'05',N'05893',N'ANTIOQUIA',N'YONDÓ',N'Municipio'),
	 (N'05',N'05895',N'ANTIOQUIA',N'ZARAGOZA',N'Municipio'),
	 (N'08',N'08001',N'ATLÁNTICO',N'BARRANQUILLA',N'Municipio'),
	 (N'08',N'08078',N'ATLÁNTICO',N'BARANOA',N'Municipio'),
	 (N'08',N'08137',N'ATLÁNTICO',N'CAMPO DE LA CRUZ',N'Municipio'),
	 (N'08',N'08141',N'ATLÁNTICO',N'CANDELARIA',N'Municipio'),
	 (N'08',N'08296',N'ATLÁNTICO',N'GALAPA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'08',N'08372',N'ATLÁNTICO',N'JUAN DE ACOSTA',N'Municipio'),
	 (N'08',N'08421',N'ATLÁNTICO',N'LURUACO',N'Municipio'),
	 (N'08',N'08433',N'ATLÁNTICO',N'MALAMBO',N'Municipio'),
	 (N'08',N'08436',N'ATLÁNTICO',N'MANATÍ',N'Municipio'),
	 (N'08',N'08520',N'ATLÁNTICO',N'PALMAR DE VARELA',N'Municipio'),
	 (N'08',N'08549',N'ATLÁNTICO',N'PIOJÓ',N'Municipio'),
	 (N'08',N'08558',N'ATLÁNTICO',N'POLONUEVO',N'Municipio'),
	 (N'08',N'08560',N'ATLÁNTICO',N'PONEDERA',N'Municipio'),
	 (N'08',N'08573',N'ATLÁNTICO',N'PUERTO COLOMBIA',N'Municipio'),
	 (N'08',N'08606',N'ATLÁNTICO',N'REPELÓN',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'08',N'08634',N'ATLÁNTICO',N'SABANAGRANDE',N'Municipio'),
	 (N'08',N'08638',N'ATLÁNTICO',N'SABANALARGA',N'Municipio'),
	 (N'08',N'08675',N'ATLÁNTICO',N'SANTA LUCÍA',N'Municipio'),
	 (N'08',N'08685',N'ATLÁNTICO',N'SANTO TOMÁS',N'Municipio'),
	 (N'08',N'08758',N'ATLÁNTICO',N'SOLEDAD',N'Municipio'),
	 (N'08',N'08770',N'ATLÁNTICO',N'SUAN',N'Municipio'),
	 (N'08',N'08832',N'ATLÁNTICO',N'TUBARÁ',N'Municipio'),
	 (N'08',N'08849',N'ATLÁNTICO',N'USIACURÍ',N'Municipio'),
	 (N'11',N'11001',N'BOGOTÁ. D.C.',N'BOGOTÁ. D.C.',N'Municipio'),
	 (N'13',N'13001',N'BOLÍVAR',N'CARTAGENA DE INDIAS',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'13',N'13006',N'BOLÍVAR',N'ACHÍ',N'Municipio'),
	 (N'13',N'13030',N'BOLÍVAR',N'ALTOS DEL ROSARIO',N'Municipio'),
	 (N'13',N'13042',N'BOLÍVAR',N'ARENAL',N'Municipio'),
	 (N'13',N'13052',N'BOLÍVAR',N'ARJONA',N'Municipio'),
	 (N'13',N'13062',N'BOLÍVAR',N'ARROYOHONDO',N'Municipio'),
	 (N'13',N'13074',N'BOLÍVAR',N'BARRANCO DE LOBA',N'Municipio'),
	 (N'13',N'13140',N'BOLÍVAR',N'CALAMAR',N'Municipio'),
	 (N'13',N'13160',N'BOLÍVAR',N'CANTAGALLO',N'Municipio'),
	 (N'13',N'13188',N'BOLÍVAR',N'CICUCO',N'Municipio'),
	 (N'13',N'13212',N'BOLÍVAR',N'CÓRDOBA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'13',N'13222',N'BOLÍVAR',N'CLEMENCIA',N'Municipio'),
	 (N'13',N'13244',N'BOLÍVAR',N'EL CARMEN DE BOLÍVAR',N'Municipio'),
	 (N'13',N'13248',N'BOLÍVAR',N'EL GUAMO',N'Municipio'),
	 (N'13',N'13268',N'BOLÍVAR',N'EL PEÑÓN',N'Municipio'),
	 (N'13',N'13300',N'BOLÍVAR',N'HATILLO DE LOBA',N'Municipio'),
	 (N'13',N'13430',N'BOLÍVAR',N'MAGANGUÉ',N'Municipio'),
	 (N'13',N'13433',N'BOLÍVAR',N'MAHATES',N'Municipio'),
	 (N'13',N'13440',N'BOLÍVAR',N'MARGARITA',N'Municipio'),
	 (N'13',N'13442',N'BOLÍVAR',N'MARÍA LA BAJA',N'Municipio'),
	 (N'13',N'13458',N'BOLÍVAR',N'MONTECRISTO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'13',N'13468',N'BOLÍVAR',N'SANTA CRUZ DE MOMPOX',N'Municipio'),
	 (N'13',N'13473',N'BOLÍVAR',N'MORALES',N'Municipio'),
	 (N'13',N'13490',N'BOLÍVAR',N'NOROSÍ',N'Municipio'),
	 (N'13',N'13549',N'BOLÍVAR',N'PINILLOS',N'Municipio'),
	 (N'13',N'13580',N'BOLÍVAR',N'REGIDOR',N'Municipio'),
	 (N'13',N'13600',N'BOLÍVAR',N'RÍO VIEJO',N'Municipio'),
	 (N'13',N'13620',N'BOLÍVAR',N'SAN CRISTÓBAL',N'Municipio'),
	 (N'13',N'13647',N'BOLÍVAR',N'SAN ESTANISLAO',N'Municipio'),
	 (N'13',N'13650',N'BOLÍVAR',N'SAN FERNANDO',N'Municipio'),
	 (N'13',N'13654',N'BOLÍVAR',N'SAN JACINTO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'13',N'13655',N'BOLÍVAR',N'SAN JACINTO DEL CAUCA',N'Municipio'),
	 (N'13',N'13657',N'BOLÍVAR',N'SAN JUAN NEPOMUCENO',N'Municipio'),
	 (N'13',N'13667',N'BOLÍVAR',N'SAN MARTÍN DE LOBA',N'Municipio'),
	 (N'13',N'13670',N'BOLÍVAR',N'SAN PABLO',N'Municipio'),
	 (N'13',N'13673',N'BOLÍVAR',N'SANTA CATALINA',N'Municipio'),
	 (N'13',N'13683',N'BOLÍVAR',N'SANTA ROSA',N'Municipio'),
	 (N'13',N'13688',N'BOLÍVAR',N'SANTA ROSA DEL SUR',N'Municipio'),
	 (N'13',N'13744',N'BOLÍVAR',N'SIMITÍ',N'Municipio'),
	 (N'13',N'13760',N'BOLÍVAR',N'SOPLAVIENTO',N'Municipio'),
	 (N'13',N'13780',N'BOLÍVAR',N'TALAIGUA NUEVO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'13',N'13810',N'BOLÍVAR',N'TIQUISIO',N'Municipio'),
	 (N'13',N'13836',N'BOLÍVAR',N'TURBACO',N'Municipio'),
	 (N'13',N'13838',N'BOLÍVAR',N'TURBANÁ',N'Municipio'),
	 (N'13',N'13873',N'BOLÍVAR',N'VILLANUEVA',N'Municipio'),
	 (N'13',N'13894',N'BOLÍVAR',N'ZAMBRANO',N'Municipio'),
	 (N'15',N'15001',N'BOYACÁ',N'TUNJA',N'Municipio'),
	 (N'15',N'15022',N'BOYACÁ',N'ALMEIDA',N'Municipio'),
	 (N'15',N'15047',N'BOYACÁ',N'AQUITANIA',N'Municipio'),
	 (N'15',N'15051',N'BOYACÁ',N'ARCABUCO',N'Municipio'),
	 (N'15',N'15087',N'BOYACÁ',N'BELÉN',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'15',N'15090',N'BOYACÁ',N'BERBEO',N'Municipio'),
	 (N'15',N'15092',N'BOYACÁ',N'BETÉITIVA',N'Municipio'),
	 (N'15',N'15097',N'BOYACÁ',N'BOAVITA',N'Municipio'),
	 (N'15',N'15104',N'BOYACÁ',N'BOYACÁ',N'Municipio'),
	 (N'15',N'15106',N'BOYACÁ',N'BRICEÑO',N'Municipio'),
	 (N'15',N'15109',N'BOYACÁ',N'BUENAVISTA',N'Municipio'),
	 (N'15',N'15114',N'BOYACÁ',N'BUSBANZÁ',N'Municipio'),
	 (N'15',N'15131',N'BOYACÁ',N'CALDAS',N'Municipio'),
	 (N'15',N'15135',N'BOYACÁ',N'CAMPOHERMOSO',N'Municipio'),
	 (N'15',N'15162',N'BOYACÁ',N'CERINZA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'15',N'15172',N'BOYACÁ',N'CHINAVITA',N'Municipio'),
	 (N'15',N'15176',N'BOYACÁ',N'CHIQUINQUIRÁ',N'Municipio'),
	 (N'15',N'15180',N'BOYACÁ',N'CHISCAS',N'Municipio'),
	 (N'15',N'15183',N'BOYACÁ',N'CHITA',N'Municipio'),
	 (N'15',N'15185',N'BOYACÁ',N'CHITARAQUE',N'Municipio'),
	 (N'15',N'15187',N'BOYACÁ',N'CHIVATÁ',N'Municipio'),
	 (N'15',N'15189',N'BOYACÁ',N'CIÉNEGA',N'Municipio'),
	 (N'15',N'15204',N'BOYACÁ',N'CÓMBITA',N'Municipio'),
	 (N'15',N'15212',N'BOYACÁ',N'COPER',N'Municipio'),
	 (N'15',N'15215',N'BOYACÁ',N'CORRALES',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'15',N'15218',N'BOYACÁ',N'COVARACHÍA',N'Municipio'),
	 (N'15',N'15223',N'BOYACÁ',N'CUBARÁ',N'Municipio'),
	 (N'19',N'19318',N'CAUCA',N'GUAPI',N'Municipio'),
	 (N'15',N'15224',N'BOYACÁ',N'CUCAITA',N'Municipio'),
	 (N'15',N'15226',N'BOYACÁ',N'CUÍTIVA',N'Municipio'),
	 (N'15',N'15232',N'BOYACÁ',N'CHÍQUIZA',N'Municipio'),
	 (N'15',N'15236',N'BOYACÁ',N'CHIVOR',N'Municipio'),
	 (N'15',N'15238',N'BOYACÁ',N'DUITAMA',N'Municipio'),
	 (N'15',N'15244',N'BOYACÁ',N'EL COCUY',N'Municipio'),
	 (N'15',N'15248',N'BOYACÁ',N'EL ESPINO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'15',N'15272',N'BOYACÁ',N'FIRAVITOBA',N'Municipio'),
	 (N'15',N'15276',N'BOYACÁ',N'FLORESTA',N'Municipio'),
	 (N'15',N'15293',N'BOYACÁ',N'GACHANTIVÁ',N'Municipio'),
	 (N'15',N'15296',N'BOYACÁ',N'GÁMEZA',N'Municipio'),
	 (N'15',N'15299',N'BOYACÁ',N'GARAGOA',N'Municipio'),
	 (N'15',N'15317',N'BOYACÁ',N'GUACAMAYAS',N'Municipio'),
	 (N'15',N'15322',N'BOYACÁ',N'GUATEQUE',N'Municipio'),
	 (N'15',N'15325',N'BOYACÁ',N'GUAYATÁ',N'Municipio'),
	 (N'15',N'15332',N'BOYACÁ',N'GÜICÁN DE LA SIERRA',N'Municipio'),
	 (N'15',N'15362',N'BOYACÁ',N'IZA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'15',N'15367',N'BOYACÁ',N'JENESANO',N'Municipio'),
	 (N'15',N'15368',N'BOYACÁ',N'JERICÓ',N'Municipio'),
	 (N'15',N'15377',N'BOYACÁ',N'LABRANZAGRANDE',N'Municipio'),
	 (N'15',N'15380',N'BOYACÁ',N'LA CAPILLA',N'Municipio'),
	 (N'15',N'15401',N'BOYACÁ',N'LA VICTORIA',N'Municipio'),
	 (N'15',N'15403',N'BOYACÁ',N'LA UVITA',N'Municipio'),
	 (N'15',N'15407',N'BOYACÁ',N'VILLA DE LEYVA',N'Municipio'),
	 (N'15',N'15425',N'BOYACÁ',N'MACANAL',N'Municipio'),
	 (N'15',N'15442',N'BOYACÁ',N'MARIPÍ',N'Municipio'),
	 (N'15',N'15455',N'BOYACÁ',N'MIRAFLORES',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'15',N'15464',N'BOYACÁ',N'MONGUA',N'Municipio'),
	 (N'15',N'15466',N'BOYACÁ',N'MONGUÍ',N'Municipio'),
	 (N'15',N'15469',N'BOYACÁ',N'MONIQUIRÁ',N'Municipio'),
	 (N'15',N'15476',N'BOYACÁ',N'MOTAVITA',N'Municipio'),
	 (N'15',N'15480',N'BOYACÁ',N'MUZO',N'Municipio'),
	 (N'15',N'15491',N'BOYACÁ',N'NOBSA',N'Municipio'),
	 (N'15',N'15494',N'BOYACÁ',N'NUEVO COLÓN',N'Municipio'),
	 (N'15',N'15500',N'BOYACÁ',N'OICATÁ',N'Municipio'),
	 (N'15',N'15507',N'BOYACÁ',N'OTANCHE',N'Municipio'),
	 (N'15',N'15511',N'BOYACÁ',N'PACHAVITA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'15',N'15514',N'BOYACÁ',N'PÁEZ',N'Municipio'),
	 (N'15',N'15516',N'BOYACÁ',N'PAIPA',N'Municipio'),
	 (N'15',N'15518',N'BOYACÁ',N'PAJARITO',N'Municipio'),
	 (N'15',N'15522',N'BOYACÁ',N'PANQUEBA',N'Municipio'),
	 (N'15',N'15531',N'BOYACÁ',N'PAUNA',N'Municipio'),
	 (N'15',N'15533',N'BOYACÁ',N'PAYA',N'Municipio'),
	 (N'15',N'15537',N'BOYACÁ',N'PAZ DE RÍO',N'Municipio'),
	 (N'15',N'15542',N'BOYACÁ',N'PESCA',N'Municipio'),
	 (N'15',N'15550',N'BOYACÁ',N'PISBA',N'Municipio'),
	 (N'15',N'15572',N'BOYACÁ',N'PUERTO BOYACÁ',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'15',N'15580',N'BOYACÁ',N'QUÍPAMA',N'Municipio'),
	 (N'15',N'15599',N'BOYACÁ',N'RAMIRIQUÍ',N'Municipio'),
	 (N'15',N'15600',N'BOYACÁ',N'RÁQUIRA',N'Municipio'),
	 (N'15',N'15621',N'BOYACÁ',N'RONDÓN',N'Municipio'),
	 (N'15',N'15632',N'BOYACÁ',N'SABOYÁ',N'Municipio'),
	 (N'15',N'15638',N'BOYACÁ',N'SÁCHICA',N'Municipio'),
	 (N'15',N'15646',N'BOYACÁ',N'SAMACÁ',N'Municipio'),
	 (N'15',N'15660',N'BOYACÁ',N'SAN EDUARDO',N'Municipio'),
	 (N'15',N'15664',N'BOYACÁ',N'SAN JOSÉ DE PARE',N'Municipio'),
	 (N'15',N'15667',N'BOYACÁ',N'SAN LUIS DE GACENO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'15',N'15673',N'BOYACÁ',N'SAN MATEO',N'Municipio'),
	 (N'15',N'15676',N'BOYACÁ',N'SAN MIGUEL DE SEMA',N'Municipio'),
	 (N'15',N'15681',N'BOYACÁ',N'SAN PABLO DE BORBUR',N'Municipio'),
	 (N'15',N'15686',N'BOYACÁ',N'SANTANA',N'Municipio'),
	 (N'15',N'15690',N'BOYACÁ',N'SANTA MARÍA',N'Municipio'),
	 (N'15',N'15693',N'BOYACÁ',N'SANTA ROSA DE VITERBO',N'Municipio'),
	 (N'15',N'15696',N'BOYACÁ',N'SANTA SOFÍA',N'Municipio'),
	 (N'15',N'15720',N'BOYACÁ',N'SATIVANORTE',N'Municipio'),
	 (N'15',N'15723',N'BOYACÁ',N'SATIVASUR',N'Municipio'),
	 (N'15',N'15740',N'BOYACÁ',N'SIACHOQUE',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'15',N'15753',N'BOYACÁ',N'SOATÁ',N'Municipio'),
	 (N'15',N'15755',N'BOYACÁ',N'SOCOTÁ',N'Municipio'),
	 (N'15',N'15757',N'BOYACÁ',N'SOCHA',N'Municipio'),
	 (N'15',N'15759',N'BOYACÁ',N'SOGAMOSO',N'Municipio'),
	 (N'15',N'15761',N'BOYACÁ',N'SOMONDOCO',N'Municipio'),
	 (N'15',N'15762',N'BOYACÁ',N'SORA',N'Municipio'),
	 (N'15',N'15763',N'BOYACÁ',N'SOTAQUIRÁ',N'Municipio'),
	 (N'15',N'15764',N'BOYACÁ',N'SORACÁ',N'Municipio'),
	 (N'15',N'15774',N'BOYACÁ',N'SUSACÓN',N'Municipio'),
	 (N'15',N'15776',N'BOYACÁ',N'SUTAMARCHÁN',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'15',N'15778',N'BOYACÁ',N'SUTATENZA',N'Municipio'),
	 (N'15',N'15790',N'BOYACÁ',N'TASCO',N'Municipio'),
	 (N'15',N'15798',N'BOYACÁ',N'TENZA',N'Municipio'),
	 (N'15',N'15804',N'BOYACÁ',N'TIBANÁ',N'Municipio'),
	 (N'15',N'15806',N'BOYACÁ',N'TIBASOSA',N'Municipio'),
	 (N'15',N'15808',N'BOYACÁ',N'TINJACÁ',N'Municipio'),
	 (N'15',N'15810',N'BOYACÁ',N'TIPACOQUE',N'Municipio'),
	 (N'15',N'15814',N'BOYACÁ',N'TOCA',N'Municipio'),
	 (N'15',N'15816',N'BOYACÁ',N'TOGÜÍ',N'Municipio'),
	 (N'15',N'15820',N'BOYACÁ',N'TÓPAGA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'15',N'15822',N'BOYACÁ',N'TOTA',N'Municipio'),
	 (N'15',N'15832',N'BOYACÁ',N'TUNUNGUÁ',N'Municipio'),
	 (N'15',N'15835',N'BOYACÁ',N'TURMEQUÉ',N'Municipio'),
	 (N'15',N'15837',N'BOYACÁ',N'TUTA',N'Municipio'),
	 (N'15',N'15839',N'BOYACÁ',N'TUTAZÁ',N'Municipio'),
	 (N'15',N'15842',N'BOYACÁ',N'ÚMBITA',N'Municipio'),
	 (N'15',N'15861',N'BOYACÁ',N'VENTAQUEMADA',N'Municipio'),
	 (N'15',N'15879',N'BOYACÁ',N'VIRACACHÁ',N'Municipio'),
	 (N'15',N'15897',N'BOYACÁ',N'ZETAQUIRA',N'Municipio'),
	 (N'17',N'17001',N'CALDAS',N'MANIZALES',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'17',N'17013',N'CALDAS',N'AGUADAS',N'Municipio'),
	 (N'17',N'17042',N'CALDAS',N'ANSERMA',N'Municipio'),
	 (N'17',N'17050',N'CALDAS',N'ARANZAZU',N'Municipio'),
	 (N'17',N'17088',N'CALDAS',N'BELALCÁZAR',N'Municipio'),
	 (N'17',N'17174',N'CALDAS',N'CHINCHINÁ',N'Municipio'),
	 (N'17',N'17272',N'CALDAS',N'FILADELFIA',N'Municipio'),
	 (N'17',N'17380',N'CALDAS',N'LA DORADA',N'Municipio'),
	 (N'17',N'17388',N'CALDAS',N'LA MERCED',N'Municipio'),
	 (N'17',N'17433',N'CALDAS',N'MANZANARES',N'Municipio'),
	 (N'17',N'17442',N'CALDAS',N'MARMATO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'17',N'17444',N'CALDAS',N'MARQUETALIA',N'Municipio'),
	 (N'17',N'17446',N'CALDAS',N'MARULANDA',N'Municipio'),
	 (N'17',N'17486',N'CALDAS',N'NEIRA',N'Municipio'),
	 (N'17',N'17495',N'CALDAS',N'NORCASIA',N'Municipio'),
	 (N'17',N'17513',N'CALDAS',N'PÁCORA',N'Municipio'),
	 (N'17',N'17524',N'CALDAS',N'PALESTINA',N'Municipio'),
	 (N'17',N'17541',N'CALDAS',N'PENSILVANIA',N'Municipio'),
	 (N'17',N'17614',N'CALDAS',N'RIOSUCIO',N'Municipio'),
	 (N'17',N'17616',N'CALDAS',N'RISARALDA',N'Municipio'),
	 (N'17',N'17653',N'CALDAS',N'SALAMINA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'17',N'17662',N'CALDAS',N'SAMANÁ',N'Municipio'),
	 (N'17',N'17665',N'CALDAS',N'SAN JOSÉ',N'Municipio'),
	 (N'17',N'17777',N'CALDAS',N'SUPÍA',N'Municipio'),
	 (N'17',N'17867',N'CALDAS',N'VICTORIA',N'Municipio'),
	 (N'17',N'17873',N'CALDAS',N'VILLAMARÍA',N'Municipio'),
	 (N'17',N'17877',N'CALDAS',N'VITERBO',N'Municipio'),
	 (N'18',N'18001',N'CAQUETÁ',N'FLORENCIA',N'Municipio'),
	 (N'18',N'18029',N'CAQUETÁ',N'ALBANIA',N'Municipio'),
	 (N'18',N'18094',N'CAQUETÁ',N'BELÉN DE LOS ANDAQUÍES',N'Municipio'),
	 (N'18',N'18150',N'CAQUETÁ',N'CARTAGENA DEL CHAIRÁ',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'18',N'18205',N'CAQUETÁ',N'CURILLO',N'Municipio'),
	 (N'18',N'18247',N'CAQUETÁ',N'EL DONCELLO',N'Municipio'),
	 (N'18',N'18256',N'CAQUETÁ',N'EL PAUJÍL',N'Municipio'),
	 (N'18',N'18410',N'CAQUETÁ',N'LA MONTAÑITA',N'Municipio'),
	 (N'18',N'18460',N'CAQUETÁ',N'MILÁN',N'Municipio'),
	 (N'18',N'18479',N'CAQUETÁ',N'MORELIA',N'Municipio'),
	 (N'18',N'18592',N'CAQUETÁ',N'PUERTO RICO',N'Municipio'),
	 (N'18',N'18610',N'CAQUETÁ',N'SAN JOSÉ DEL FRAGUA',N'Municipio'),
	 (N'18',N'18753',N'CAQUETÁ',N'SAN VICENTE DEL CAGUÁN',N'Municipio'),
	 (N'18',N'18756',N'CAQUETÁ',N'SOLANO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'18',N'18785',N'CAQUETÁ',N'SOLITA',N'Municipio'),
	 (N'18',N'18860',N'CAQUETÁ',N'VALPARAÍSO',N'Municipio'),
	 (N'19',N'19001',N'CAUCA',N'POPAYÁN',N'Municipio'),
	 (N'19',N'19022',N'CAUCA',N'ALMAGUER',N'Municipio'),
	 (N'19',N'19050',N'CAUCA',N'ARGELIA',N'Municipio'),
	 (N'19',N'19075',N'CAUCA',N'BALBOA',N'Municipio'),
	 (N'19',N'19100',N'CAUCA',N'BOLÍVAR',N'Municipio'),
	 (N'19',N'19110',N'CAUCA',N'BUENOS AIRES',N'Municipio'),
	 (N'19',N'19130',N'CAUCA',N'CAJIBÍO',N'Municipio'),
	 (N'19',N'19137',N'CAUCA',N'CALDONO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'19',N'19142',N'CAUCA',N'CALOTO',N'Municipio'),
	 (N'19',N'19212',N'CAUCA',N'CORINTO',N'Municipio'),
	 (N'19',N'19256',N'CAUCA',N'EL TAMBO',N'Municipio'),
	 (N'19',N'19290',N'CAUCA',N'FLORENCIA',N'Municipio'),
	 (N'19',N'19300',N'CAUCA',N'GUACHENÉ',N'Municipio'),
	 (N'19',N'19355',N'CAUCA',N'INZÁ',N'Municipio'),
	 (N'19',N'19364',N'CAUCA',N'JAMBALÓ',N'Municipio'),
	 (N'19',N'19392',N'CAUCA',N'LA SIERRA',N'Municipio'),
	 (N'19',N'19397',N'CAUCA',N'LA VEGA',N'Municipio'),
	 (N'19',N'19418',N'CAUCA',N'LÓPEZ DE MICAY',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'19',N'19450',N'CAUCA',N'MERCADERES',N'Municipio'),
	 (N'19',N'19455',N'CAUCA',N'MIRANDA',N'Municipio'),
	 (N'19',N'19473',N'CAUCA',N'MORALES',N'Municipio'),
	 (N'19',N'19513',N'CAUCA',N'PADILLA',N'Municipio'),
	 (N'19',N'19517',N'CAUCA',N'PÁEZ',N'Municipio'),
	 (N'19',N'19532',N'CAUCA',N'PATÍA',N'Municipio'),
	 (N'19',N'19533',N'CAUCA',N'PIAMONTE',N'Municipio'),
	 (N'19',N'19548',N'CAUCA',N'PIENDAMÓ - TUNÍA',N'Municipio'),
	 (N'19',N'19573',N'CAUCA',N'PUERTO TEJADA',N'Municipio'),
	 (N'19',N'19585',N'CAUCA',N'PURACÉ',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'19',N'19622',N'CAUCA',N'ROSAS',N'Municipio'),
	 (N'19',N'19693',N'CAUCA',N'SAN SEBASTIÁN',N'Municipio'),
	 (N'19',N'19698',N'CAUCA',N'SANTANDER DE QUILICHAO',N'Municipio'),
	 (N'19',N'19701',N'CAUCA',N'SANTA ROSA',N'Municipio'),
	 (N'19',N'19743',N'CAUCA',N'SILVIA',N'Municipio'),
	 (N'19',N'19760',N'CAUCA',N'SOTARÁ PAISPAMBA',N'Municipio'),
	 (N'19',N'19780',N'CAUCA',N'SUÁREZ',N'Municipio'),
	 (N'19',N'19785',N'CAUCA',N'SUCRE',N'Municipio'),
	 (N'19',N'19807',N'CAUCA',N'TIMBÍO',N'Municipio'),
	 (N'19',N'19809',N'CAUCA',N'TIMBIQUÍ',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'19',N'19821',N'CAUCA',N'TORIBÍO',N'Municipio'),
	 (N'19',N'19824',N'CAUCA',N'TOTORÓ',N'Municipio'),
	 (N'19',N'19845',N'CAUCA',N'VILLA RICA',N'Municipio'),
	 (N'20',N'20001',N'CESAR',N'VALLEDUPAR',N'Municipio'),
	 (N'20',N'20011',N'CESAR',N'AGUACHICA',N'Municipio'),
	 (N'20',N'20013',N'CESAR',N'AGUSTÍN CODAZZI',N'Municipio'),
	 (N'20',N'20032',N'CESAR',N'ASTREA',N'Municipio'),
	 (N'20',N'20045',N'CESAR',N'BECERRIL',N'Municipio'),
	 (N'20',N'20060',N'CESAR',N'BOSCONIA',N'Municipio'),
	 (N'20',N'20175',N'CESAR',N'CHIMICHAGUA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'20',N'20178',N'CESAR',N'CHIRIGUANÁ',N'Municipio'),
	 (N'20',N'20228',N'CESAR',N'CURUMANÍ',N'Municipio'),
	 (N'20',N'20238',N'CESAR',N'EL COPEY',N'Municipio'),
	 (N'20',N'20250',N'CESAR',N'EL PASO',N'Municipio'),
	 (N'20',N'20295',N'CESAR',N'GAMARRA',N'Municipio'),
	 (N'20',N'20310',N'CESAR',N'GONZÁLEZ',N'Municipio'),
	 (N'20',N'20383',N'CESAR',N'LA GLORIA',N'Municipio'),
	 (N'20',N'20400',N'CESAR',N'LA JAGUA DE IBIRICO',N'Municipio'),
	 (N'20',N'20443',N'CESAR',N'MANAURE BALCÓN DEL CESAR',N'Municipio'),
	 (N'20',N'20517',N'CESAR',N'PAILITAS',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'20',N'20550',N'CESAR',N'PELAYA',N'Municipio'),
	 (N'20',N'20570',N'CESAR',N'PUEBLO BELLO',N'Municipio'),
	 (N'20',N'20614',N'CESAR',N'RÍO DE ORO',N'Municipio'),
	 (N'20',N'20621',N'CESAR',N'LA PAZ',N'Municipio'),
	 (N'20',N'20710',N'CESAR',N'SAN ALBERTO',N'Municipio'),
	 (N'20',N'20750',N'CESAR',N'SAN DIEGO',N'Municipio'),
	 (N'20',N'20770',N'CESAR',N'SAN MARTÍN',N'Municipio'),
	 (N'20',N'20787',N'CESAR',N'TAMALAMEQUE',N'Municipio'),
	 (N'23',N'23001',N'CÓRDOBA',N'MONTERÍA',N'Municipio'),
	 (N'23',N'23068',N'CÓRDOBA',N'AYAPEL',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'23',N'23079',N'CÓRDOBA',N'BUENAVISTA',N'Municipio'),
	 (N'23',N'23090',N'CÓRDOBA',N'CANALETE',N'Municipio'),
	 (N'23',N'23162',N'CÓRDOBA',N'CERETÉ',N'Municipio'),
	 (N'23',N'23168',N'CÓRDOBA',N'CHIMÁ',N'Municipio'),
	 (N'23',N'23182',N'CÓRDOBA',N'CHINÚ',N'Municipio'),
	 (N'23',N'23189',N'CÓRDOBA',N'CIÉNAGA DE ORO',N'Municipio'),
	 (N'23',N'23300',N'CÓRDOBA',N'COTORRA',N'Municipio'),
	 (N'23',N'23350',N'CÓRDOBA',N'LA APARTADA',N'Municipio'),
	 (N'23',N'23417',N'CÓRDOBA',N'LORICA',N'Municipio'),
	 (N'23',N'23419',N'CÓRDOBA',N'LOS CÓRDOBAS',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'23',N'23464',N'CÓRDOBA',N'MOMIL',N'Municipio'),
	 (N'23',N'23466',N'CÓRDOBA',N'MONTELÍBANO',N'Municipio'),
	 (N'23',N'23500',N'CÓRDOBA',N'MOÑITOS',N'Municipio'),
	 (N'23',N'23555',N'CÓRDOBA',N'PLANETA RICA',N'Municipio'),
	 (N'23',N'23570',N'CÓRDOBA',N'PUEBLO NUEVO',N'Municipio'),
	 (N'23',N'23574',N'CÓRDOBA',N'PUERTO ESCONDIDO',N'Municipio'),
	 (N'23',N'23580',N'CÓRDOBA',N'PUERTO LIBERTADOR',N'Municipio'),
	 (N'23',N'23586',N'CÓRDOBA',N'PURÍSIMA DE LA CONCEPCIÓN',N'Municipio'),
	 (N'23',N'23660',N'CÓRDOBA',N'SAHAGÚN',N'Municipio'),
	 (N'23',N'23670',N'CÓRDOBA',N'SAN ANDRÉS DE SOTAVENTO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'23',N'23672',N'CÓRDOBA',N'SAN ANTERO',N'Municipio'),
	 (N'23',N'23675',N'CÓRDOBA',N'SAN BERNARDO DEL VIENTO',N'Municipio'),
	 (N'23',N'23678',N'CÓRDOBA',N'SAN CARLOS',N'Municipio'),
	 (N'23',N'23682',N'CÓRDOBA',N'SAN JOSÉ DE URÉ',N'Municipio'),
	 (N'23',N'23686',N'CÓRDOBA',N'SAN PELAYO',N'Municipio'),
	 (N'23',N'23807',N'CÓRDOBA',N'TIERRALTA',N'Municipio'),
	 (N'23',N'23815',N'CÓRDOBA',N'TUCHÍN',N'Municipio'),
	 (N'23',N'23855',N'CÓRDOBA',N'VALENCIA',N'Municipio'),
	 (N'25',N'25001',N'CUNDINAMARCA',N'AGUA DE DIOS',N'Municipio'),
	 (N'25',N'25019',N'CUNDINAMARCA',N'ALBÁN',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'25',N'25035',N'CUNDINAMARCA',N'ANAPOIMA',N'Municipio'),
	 (N'25',N'25040',N'CUNDINAMARCA',N'ANOLAIMA',N'Municipio'),
	 (N'25',N'25053',N'CUNDINAMARCA',N'ARBELÁEZ',N'Municipio'),
	 (N'25',N'25086',N'CUNDINAMARCA',N'BELTRÁN',N'Municipio'),
	 (N'25',N'25095',N'CUNDINAMARCA',N'BITUIMA',N'Municipio'),
	 (N'25',N'25099',N'CUNDINAMARCA',N'BOJACÁ',N'Municipio'),
	 (N'25',N'25120',N'CUNDINAMARCA',N'CABRERA',N'Municipio'),
	 (N'25',N'25123',N'CUNDINAMARCA',N'CACHIPAY',N'Municipio'),
	 (N'25',N'25126',N'CUNDINAMARCA',N'CAJICÁ',N'Municipio'),
	 (N'25',N'25148',N'CUNDINAMARCA',N'CAPARRAPÍ',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'25',N'25151',N'CUNDINAMARCA',N'CÁQUEZA',N'Municipio'),
	 (N'25',N'25154',N'CUNDINAMARCA',N'CARMEN DE CARUPA',N'Municipio'),
	 (N'25',N'25168',N'CUNDINAMARCA',N'CHAGUANÍ',N'Municipio'),
	 (N'25',N'25175',N'CUNDINAMARCA',N'CHÍA',N'Municipio'),
	 (N'25',N'25178',N'CUNDINAMARCA',N'CHIPAQUE',N'Municipio'),
	 (N'25',N'25181',N'CUNDINAMARCA',N'CHOACHÍ',N'Municipio'),
	 (N'25',N'25183',N'CUNDINAMARCA',N'CHOCONTÁ',N'Municipio'),
	 (N'25',N'25200',N'CUNDINAMARCA',N'COGUA',N'Municipio'),
	 (N'25',N'25214',N'CUNDINAMARCA',N'COTA',N'Municipio'),
	 (N'25',N'25224',N'CUNDINAMARCA',N'CUCUNUBÁ',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'25',N'25245',N'CUNDINAMARCA',N'EL COLEGIO',N'Municipio'),
	 (N'25',N'25258',N'CUNDINAMARCA',N'EL PEÑÓN',N'Municipio'),
	 (N'25',N'25260',N'CUNDINAMARCA',N'EL ROSAL',N'Municipio'),
	 (N'25',N'25269',N'CUNDINAMARCA',N'FACATATIVÁ',N'Municipio'),
	 (N'25',N'25279',N'CUNDINAMARCA',N'FÓMEQUE',N'Municipio'),
	 (N'25',N'25281',N'CUNDINAMARCA',N'FOSCA',N'Municipio'),
	 (N'25',N'25286',N'CUNDINAMARCA',N'FUNZA',N'Municipio'),
	 (N'25',N'25288',N'CUNDINAMARCA',N'FÚQUENE',N'Municipio'),
	 (N'25',N'25290',N'CUNDINAMARCA',N'FUSAGASUGÁ',N'Municipio'),
	 (N'25',N'25293',N'CUNDINAMARCA',N'GACHALÁ',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'25',N'25295',N'CUNDINAMARCA',N'GACHANCIPÁ',N'Municipio'),
	 (N'25',N'25297',N'CUNDINAMARCA',N'GACHETÁ',N'Municipio'),
	 (N'25',N'25299',N'CUNDINAMARCA',N'GAMA',N'Municipio'),
	 (N'25',N'25307',N'CUNDINAMARCA',N'GIRARDOT',N'Municipio'),
	 (N'25',N'25312',N'CUNDINAMARCA',N'GRANADA',N'Municipio'),
	 (N'25',N'25317',N'CUNDINAMARCA',N'GUACHETÁ',N'Municipio'),
	 (N'25',N'25320',N'CUNDINAMARCA',N'GUADUAS',N'Municipio'),
	 (N'25',N'25322',N'CUNDINAMARCA',N'GUASCA',N'Municipio'),
	 (N'25',N'25324',N'CUNDINAMARCA',N'GUATAQUÍ',N'Municipio'),
	 (N'25',N'25326',N'CUNDINAMARCA',N'GUATAVITA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'25',N'25328',N'CUNDINAMARCA',N'GUAYABAL DE SÍQUIMA',N'Municipio'),
	 (N'25',N'25335',N'CUNDINAMARCA',N'GUAYABETAL',N'Municipio'),
	 (N'25',N'25339',N'CUNDINAMARCA',N'GUTIÉRREZ',N'Municipio'),
	 (N'25',N'25368',N'CUNDINAMARCA',N'JERUSALÉN',N'Municipio'),
	 (N'25',N'25372',N'CUNDINAMARCA',N'JUNÍN',N'Municipio'),
	 (N'25',N'25377',N'CUNDINAMARCA',N'LA CALERA',N'Municipio'),
	 (N'25',N'25386',N'CUNDINAMARCA',N'LA MESA',N'Municipio'),
	 (N'25',N'25394',N'CUNDINAMARCA',N'LA PALMA',N'Municipio'),
	 (N'25',N'25398',N'CUNDINAMARCA',N'LA PEÑA',N'Municipio'),
	 (N'25',N'25402',N'CUNDINAMARCA',N'LA VEGA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'25',N'25407',N'CUNDINAMARCA',N'LENGUAZAQUE',N'Municipio'),
	 (N'25',N'25426',N'CUNDINAMARCA',N'MACHETÁ',N'Municipio'),
	 (N'25',N'25430',N'CUNDINAMARCA',N'MADRID',N'Municipio'),
	 (N'25',N'25436',N'CUNDINAMARCA',N'MANTA',N'Municipio'),
	 (N'25',N'25438',N'CUNDINAMARCA',N'MEDINA',N'Municipio'),
	 (N'25',N'25473',N'CUNDINAMARCA',N'MOSQUERA',N'Municipio'),
	 (N'25',N'25483',N'CUNDINAMARCA',N'NARIÑO',N'Municipio'),
	 (N'25',N'25486',N'CUNDINAMARCA',N'NEMOCÓN',N'Municipio'),
	 (N'25',N'25488',N'CUNDINAMARCA',N'NILO',N'Municipio'),
	 (N'25',N'25489',N'CUNDINAMARCA',N'NIMAIMA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'25',N'25491',N'CUNDINAMARCA',N'NOCAIMA',N'Municipio'),
	 (N'25',N'25506',N'CUNDINAMARCA',N'VENECIA',N'Municipio'),
	 (N'25',N'25513',N'CUNDINAMARCA',N'PACHO',N'Municipio'),
	 (N'25',N'25518',N'CUNDINAMARCA',N'PAIME',N'Municipio'),
	 (N'25',N'25524',N'CUNDINAMARCA',N'PANDI',N'Municipio'),
	 (N'25',N'25530',N'CUNDINAMARCA',N'PARATEBUENO',N'Municipio'),
	 (N'25',N'25535',N'CUNDINAMARCA',N'PASCA',N'Municipio'),
	 (N'25',N'25572',N'CUNDINAMARCA',N'PUERTO SALGAR',N'Municipio'),
	 (N'25',N'25580',N'CUNDINAMARCA',N'PULÍ',N'Municipio'),
	 (N'25',N'25592',N'CUNDINAMARCA',N'QUEBRADANEGRA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'25',N'25594',N'CUNDINAMARCA',N'QUETAME',N'Municipio'),
	 (N'25',N'25596',N'CUNDINAMARCA',N'QUIPILE',N'Municipio'),
	 (N'25',N'25599',N'CUNDINAMARCA',N'APULO',N'Municipio'),
	 (N'25',N'25612',N'CUNDINAMARCA',N'RICAURTE',N'Municipio'),
	 (N'25',N'25645',N'CUNDINAMARCA',N'SAN ANTONIO DEL TEQUENDAMA',N'Municipio'),
	 (N'25',N'25649',N'CUNDINAMARCA',N'SAN BERNARDO',N'Municipio'),
	 (N'25',N'25653',N'CUNDINAMARCA',N'SAN CAYETANO',N'Municipio'),
	 (N'25',N'25658',N'CUNDINAMARCA',N'SAN FRANCISCO',N'Municipio'),
	 (N'25',N'25662',N'CUNDINAMARCA',N'SAN JUAN DE RIOSECO',N'Municipio'),
	 (N'25',N'25718',N'CUNDINAMARCA',N'SASAIMA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'25',N'25736',N'CUNDINAMARCA',N'SESQUILÉ',N'Municipio'),
	 (N'25',N'25740',N'CUNDINAMARCA',N'SIBATÉ',N'Municipio'),
	 (N'25',N'25743',N'CUNDINAMARCA',N'SILVANIA',N'Municipio'),
	 (N'25',N'25745',N'CUNDINAMARCA',N'SIMIJACA',N'Municipio'),
	 (N'25',N'25754',N'CUNDINAMARCA',N'SOACHA',N'Municipio'),
	 (N'25',N'25758',N'CUNDINAMARCA',N'SOPÓ',N'Municipio'),
	 (N'25',N'25769',N'CUNDINAMARCA',N'SUBACHOQUE',N'Municipio'),
	 (N'25',N'25772',N'CUNDINAMARCA',N'SUESCA',N'Municipio'),
	 (N'25',N'25777',N'CUNDINAMARCA',N'SUPATÁ',N'Municipio'),
	 (N'25',N'25779',N'CUNDINAMARCA',N'SUSA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'25',N'25781',N'CUNDINAMARCA',N'SUTATAUSA',N'Municipio'),
	 (N'25',N'25785',N'CUNDINAMARCA',N'TABIO',N'Municipio'),
	 (N'25',N'25793',N'CUNDINAMARCA',N'TAUSA',N'Municipio'),
	 (N'25',N'25797',N'CUNDINAMARCA',N'TENA',N'Municipio'),
	 (N'25',N'25799',N'CUNDINAMARCA',N'TENJO',N'Municipio'),
	 (N'25',N'25805',N'CUNDINAMARCA',N'TIBACUY',N'Municipio'),
	 (N'25',N'25807',N'CUNDINAMARCA',N'TIBIRITA',N'Municipio'),
	 (N'25',N'25815',N'CUNDINAMARCA',N'TOCAIMA',N'Municipio'),
	 (N'25',N'25817',N'CUNDINAMARCA',N'TOCANCIPÁ',N'Municipio'),
	 (N'25',N'25823',N'CUNDINAMARCA',N'TOPAIPÍ',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'25',N'25839',N'CUNDINAMARCA',N'UBALÁ',N'Municipio'),
	 (N'25',N'25841',N'CUNDINAMARCA',N'UBAQUE',N'Municipio'),
	 (N'25',N'25843',N'CUNDINAMARCA',N'VILLA DE SAN DIEGO DE UBATÉ',N'Municipio'),
	 (N'25',N'25845',N'CUNDINAMARCA',N'UNE',N'Municipio'),
	 (N'25',N'25851',N'CUNDINAMARCA',N'ÚTICA',N'Municipio'),
	 (N'25',N'25862',N'CUNDINAMARCA',N'VERGARA',N'Municipio'),
	 (N'25',N'25867',N'CUNDINAMARCA',N'VIANÍ',N'Municipio'),
	 (N'25',N'25871',N'CUNDINAMARCA',N'VILLAGÓMEZ',N'Municipio'),
	 (N'25',N'25873',N'CUNDINAMARCA',N'VILLAPINZÓN',N'Municipio'),
	 (N'25',N'25875',N'CUNDINAMARCA',N'VILLETA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'25',N'25878',N'CUNDINAMARCA',N'VIOTÁ',N'Municipio'),
	 (N'25',N'25885',N'CUNDINAMARCA',N'YACOPÍ',N'Municipio'),
	 (N'25',N'25898',N'CUNDINAMARCA',N'ZIPACÓN',N'Municipio'),
	 (N'25',N'25899',N'CUNDINAMARCA',N'ZIPAQUIRÁ',N'Municipio'),
	 (N'27',N'27001',N'CHOCÓ',N'QUIBDÓ',N'Municipio'),
	 (N'27',N'27006',N'CHOCÓ',N'ACANDÍ',N'Municipio'),
	 (N'27',N'27025',N'CHOCÓ',N'ALTO BAUDÓ',N'Municipio'),
	 (N'27',N'27050',N'CHOCÓ',N'ATRATO',N'Municipio'),
	 (N'27',N'27073',N'CHOCÓ',N'BAGADÓ',N'Municipio'),
	 (N'27',N'27075',N'CHOCÓ',N'BAHÍA SOLANO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'27',N'27077',N'CHOCÓ',N'BAJO BAUDÓ',N'Municipio'),
	 (N'27',N'27099',N'CHOCÓ',N'BOJAYÁ',N'Municipio'),
	 (N'27',N'27135',N'CHOCÓ',N'EL CANTÓN DEL SAN PABLO',N'Municipio'),
	 (N'27',N'27150',N'CHOCÓ',N'CARMEN DEL DARIÉN',N'Municipio'),
	 (N'27',N'27160',N'CHOCÓ',N'CÉRTEGUI',N'Municipio'),
	 (N'27',N'27205',N'CHOCÓ',N'CONDOTO',N'Municipio'),
	 (N'27',N'27245',N'CHOCÓ',N'EL CARMEN DE ATRATO',N'Municipio'),
	 (N'27',N'27250',N'CHOCÓ',N'EL LITORAL DEL SAN JUAN',N'Municipio'),
	 (N'27',N'27361',N'CHOCÓ',N'ISTMINA',N'Municipio'),
	 (N'27',N'27372',N'CHOCÓ',N'JURADÓ',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'27',N'27413',N'CHOCÓ',N'LLORÓ',N'Municipio'),
	 (N'27',N'27425',N'CHOCÓ',N'MEDIO ATRATO',N'Municipio'),
	 (N'27',N'27430',N'CHOCÓ',N'MEDIO BAUDÓ',N'Municipio'),
	 (N'27',N'27450',N'CHOCÓ',N'MEDIO SAN JUAN',N'Municipio'),
	 (N'27',N'27491',N'CHOCÓ',N'NÓVITA',N'Municipio'),
	 (N'27',N'27495',N'CHOCÓ',N'NUQUÍ',N'Municipio'),
	 (N'27',N'27580',N'CHOCÓ',N'RÍO IRÓ',N'Municipio'),
	 (N'27',N'27600',N'CHOCÓ',N'RÍO QUITO',N'Municipio'),
	 (N'27',N'27615',N'CHOCÓ',N'RIOSUCIO',N'Municipio'),
	 (N'27',N'27660',N'CHOCÓ',N'SAN JOSÉ DEL PALMAR',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'27',N'27745',N'CHOCÓ',N'SIPÍ',N'Municipio'),
	 (N'27',N'27787',N'CHOCÓ',N'TADÓ',N'Municipio'),
	 (N'27',N'27800',N'CHOCÓ',N'UNGUÍA',N'Municipio'),
	 (N'27',N'27810',N'CHOCÓ',N'UNIÓN PANAMERICANA',N'Municipio'),
	 (N'41',N'41001',N'HUILA',N'NEIVA',N'Municipio'),
	 (N'41',N'41006',N'HUILA',N'ACEVEDO',N'Municipio'),
	 (N'41',N'41013',N'HUILA',N'AGRADO',N'Municipio'),
	 (N'41',N'41016',N'HUILA',N'AIPE',N'Municipio'),
	 (N'41',N'41020',N'HUILA',N'ALGECIRAS',N'Municipio'),
	 (N'41',N'41026',N'HUILA',N'ALTAMIRA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'41',N'41078',N'HUILA',N'BARAYA',N'Municipio'),
	 (N'41',N'41132',N'HUILA',N'CAMPOALEGRE',N'Municipio'),
	 (N'41',N'41206',N'HUILA',N'COLOMBIA',N'Municipio'),
	 (N'41',N'41244',N'HUILA',N'ELÍAS',N'Municipio'),
	 (N'41',N'41298',N'HUILA',N'GARZÓN',N'Municipio'),
	 (N'41',N'41306',N'HUILA',N'GIGANTE',N'Municipio'),
	 (N'41',N'41319',N'HUILA',N'GUADALUPE',N'Municipio'),
	 (N'41',N'41349',N'HUILA',N'HOBO',N'Municipio'),
	 (N'41',N'41357',N'HUILA',N'ÍQUIRA',N'Municipio'),
	 (N'41',N'41359',N'HUILA',N'ISNOS',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'41',N'41378',N'HUILA',N'LA ARGENTINA',N'Municipio'),
	 (N'41',N'41396',N'HUILA',N'LA PLATA',N'Municipio'),
	 (N'41',N'41483',N'HUILA',N'NÁTAGA',N'Municipio'),
	 (N'41',N'41503',N'HUILA',N'OPORAPA',N'Municipio'),
	 (N'41',N'41518',N'HUILA',N'PAICOL',N'Municipio'),
	 (N'41',N'41524',N'HUILA',N'PALERMO',N'Municipio'),
	 (N'41',N'41530',N'HUILA',N'PALESTINA',N'Municipio'),
	 (N'41',N'41548',N'HUILA',N'PITAL',N'Municipio'),
	 (N'41',N'41551',N'HUILA',N'PITALITO',N'Municipio'),
	 (N'41',N'41615',N'HUILA',N'RIVERA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'41',N'41660',N'HUILA',N'SALADOBLANCO',N'Municipio'),
	 (N'41',N'41668',N'HUILA',N'SAN AGUSTÍN',N'Municipio'),
	 (N'41',N'41676',N'HUILA',N'SANTA MARÍA',N'Municipio'),
	 (N'41',N'41770',N'HUILA',N'SUAZA',N'Municipio'),
	 (N'41',N'41791',N'HUILA',N'TARQUI',N'Municipio'),
	 (N'41',N'41797',N'HUILA',N'TESALIA',N'Municipio'),
	 (N'41',N'41799',N'HUILA',N'TELLO',N'Municipio'),
	 (N'41',N'41801',N'HUILA',N'TERUEL',N'Municipio'),
	 (N'41',N'41807',N'HUILA',N'TIMANÁ',N'Municipio'),
	 (N'41',N'41872',N'HUILA',N'VILLAVIEJA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'41',N'41885',N'HUILA',N'YAGUARÁ',N'Municipio'),
	 (N'44',N'44001',N'LA GUAJIRA',N'RIOHACHA',N'Municipio'),
	 (N'44',N'44035',N'LA GUAJIRA',N'ALBANIA',N'Municipio'),
	 (N'44',N'44078',N'LA GUAJIRA',N'BARRANCAS',N'Municipio'),
	 (N'44',N'44090',N'LA GUAJIRA',N'DIBULLA',N'Municipio'),
	 (N'44',N'44098',N'LA GUAJIRA',N'DISTRACCIÓN',N'Municipio'),
	 (N'44',N'44110',N'LA GUAJIRA',N'EL MOLINO',N'Municipio'),
	 (N'44',N'44279',N'LA GUAJIRA',N'FONSECA',N'Municipio'),
	 (N'44',N'44378',N'LA GUAJIRA',N'HATONUEVO',N'Municipio'),
	 (N'44',N'44420',N'LA GUAJIRA',N'LA JAGUA DEL PILAR',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'44',N'44430',N'LA GUAJIRA',N'MAICAO',N'Municipio'),
	 (N'44',N'44560',N'LA GUAJIRA',N'MANAURE',N'Municipio'),
	 (N'44',N'44650',N'LA GUAJIRA',N'SAN JUAN DEL CESAR',N'Municipio'),
	 (N'44',N'44847',N'LA GUAJIRA',N'URIBIA',N'Municipio'),
	 (N'44',N'44855',N'LA GUAJIRA',N'URUMITA',N'Municipio'),
	 (N'44',N'44874',N'LA GUAJIRA',N'VILLANUEVA',N'Municipio'),
	 (N'47',N'47001',N'MAGDALENA',N'SANTA MARTA',N'Municipio'),
	 (N'47',N'47030',N'MAGDALENA',N'ALGARROBO',N'Municipio'),
	 (N'47',N'47053',N'MAGDALENA',N'ARACATACA',N'Municipio'),
	 (N'47',N'47058',N'MAGDALENA',N'ARIGUANÍ',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'47',N'47161',N'MAGDALENA',N'CERRO DE SAN ANTONIO',N'Municipio'),
	 (N'47',N'47170',N'MAGDALENA',N'CHIVOLO',N'Municipio'),
	 (N'47',N'47189',N'MAGDALENA',N'CIÉNAGA',N'Municipio'),
	 (N'47',N'47205',N'MAGDALENA',N'CONCORDIA',N'Municipio'),
	 (N'47',N'47245',N'MAGDALENA',N'EL BANCO',N'Municipio'),
	 (N'47',N'47258',N'MAGDALENA',N'EL PIÑÓN',N'Municipio'),
	 (N'47',N'47268',N'MAGDALENA',N'EL RETÉN',N'Municipio'),
	 (N'47',N'47288',N'MAGDALENA',N'FUNDACIÓN',N'Municipio'),
	 (N'47',N'47318',N'MAGDALENA',N'GUAMAL',N'Municipio'),
	 (N'47',N'47460',N'MAGDALENA',N'NUEVA GRANADA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'47',N'47541',N'MAGDALENA',N'PEDRAZA',N'Municipio'),
	 (N'47',N'47545',N'MAGDALENA',N'PIJIÑO DEL CARMEN',N'Municipio'),
	 (N'47',N'47551',N'MAGDALENA',N'PIVIJAY',N'Municipio'),
	 (N'47',N'47555',N'MAGDALENA',N'PLATO',N'Municipio'),
	 (N'47',N'47570',N'MAGDALENA',N'PUEBLOVIEJO',N'Municipio'),
	 (N'47',N'47605',N'MAGDALENA',N'REMOLINO',N'Municipio'),
	 (N'47',N'47660',N'MAGDALENA',N'SABANAS DE SAN ÁNGEL',N'Municipio'),
	 (N'47',N'47675',N'MAGDALENA',N'SALAMINA',N'Municipio'),
	 (N'47',N'47692',N'MAGDALENA',N'SAN SEBASTIÁN DE BUENAVISTA',N'Municipio'),
	 (N'47',N'47703',N'MAGDALENA',N'SAN ZENÓN',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'47',N'47707',N'MAGDALENA',N'SANTA ANA',N'Municipio'),
	 (N'47',N'47720',N'MAGDALENA',N'SANTA BÁRBARA DE PINTO',N'Municipio'),
	 (N'47',N'47745',N'MAGDALENA',N'SITIONUEVO',N'Municipio'),
	 (N'47',N'47798',N'MAGDALENA',N'TENERIFE',N'Municipio'),
	 (N'47',N'47960',N'MAGDALENA',N'ZAPAYÁN',N'Municipio'),
	 (N'47',N'47980',N'MAGDALENA',N'ZONA BANANERA',N'Municipio'),
	 (N'50',N'50001',N'META',N'VILLAVICENCIO',N'Municipio'),
	 (N'50',N'50006',N'META',N'ACACÍAS',N'Municipio'),
	 (N'50',N'50110',N'META',N'BARRANCA DE UPÍA',N'Municipio'),
	 (N'50',N'50124',N'META',N'CABUYARO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'50',N'50150',N'META',N'CASTILLA LA NUEVA',N'Municipio'),
	 (N'50',N'50223',N'META',N'CUBARRAL',N'Municipio'),
	 (N'50',N'50226',N'META',N'CUMARAL',N'Municipio'),
	 (N'50',N'50245',N'META',N'EL CALVARIO',N'Municipio'),
	 (N'50',N'50251',N'META',N'EL CASTILLO',N'Municipio'),
	 (N'50',N'50270',N'META',N'EL DORADO',N'Municipio'),
	 (N'50',N'50287',N'META',N'FUENTE DE ORO',N'Municipio'),
	 (N'50',N'50313',N'META',N'GRANADA',N'Municipio'),
	 (N'50',N'50318',N'META',N'GUAMAL',N'Municipio'),
	 (N'50',N'50325',N'META',N'MAPIRIPÁN',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'50',N'50330',N'META',N'MESETAS',N'Municipio'),
	 (N'50',N'50350',N'META',N'LA MACARENA',N'Municipio'),
	 (N'50',N'50370',N'META',N'URIBE',N'Municipio'),
	 (N'50',N'50400',N'META',N'LEJANÍAS',N'Municipio'),
	 (N'50',N'50450',N'META',N'PUERTO CONCORDIA',N'Municipio'),
	 (N'50',N'50568',N'META',N'PUERTO GAITÁN',N'Municipio'),
	 (N'50',N'50573',N'META',N'PUERTO LÓPEZ',N'Municipio'),
	 (N'50',N'50577',N'META',N'PUERTO LLERAS',N'Municipio'),
	 (N'50',N'50590',N'META',N'PUERTO RICO',N'Municipio'),
	 (N'50',N'50606',N'META',N'RESTREPO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'50',N'50680',N'META',N'SAN CARLOS DE GUAROA',N'Municipio'),
	 (N'50',N'50683',N'META',N'SAN JUAN DE ARAMA',N'Municipio'),
	 (N'50',N'50686',N'META',N'SAN JUANITO',N'Municipio'),
	 (N'50',N'50689',N'META',N'SAN MARTÍN',N'Municipio'),
	 (N'50',N'50711',N'META',N'VISTAHERMOSA',N'Municipio'),
	 (N'52',N'52001',N'NARIÑO',N'PASTO',N'Municipio'),
	 (N'52',N'52019',N'NARIÑO',N'ALBÁN',N'Municipio'),
	 (N'52',N'52022',N'NARIÑO',N'ALDANA',N'Municipio'),
	 (N'52',N'52036',N'NARIÑO',N'ANCUYA',N'Municipio'),
	 (N'52',N'52051',N'NARIÑO',N'ARBOLEDA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'52',N'52079',N'NARIÑO',N'BARBACOAS',N'Municipio'),
	 (N'52',N'52083',N'NARIÑO',N'BELÉN',N'Municipio'),
	 (N'52',N'52110',N'NARIÑO',N'BUESACO',N'Municipio'),
	 (N'52',N'52203',N'NARIÑO',N'COLÓN',N'Municipio'),
	 (N'52',N'52207',N'NARIÑO',N'CONSACÁ',N'Municipio'),
	 (N'52',N'52210',N'NARIÑO',N'CONTADERO',N'Municipio'),
	 (N'52',N'52215',N'NARIÑO',N'CÓRDOBA',N'Municipio'),
	 (N'52',N'52224',N'NARIÑO',N'CUASPUD CARLOSAMA',N'Municipio'),
	 (N'52',N'52227',N'NARIÑO',N'CUMBAL',N'Municipio'),
	 (N'52',N'52233',N'NARIÑO',N'CUMBITARA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'52',N'52240',N'NARIÑO',N'CHACHAGÜÍ',N'Municipio'),
	 (N'52',N'52250',N'NARIÑO',N'EL CHARCO',N'Municipio'),
	 (N'52',N'52254',N'NARIÑO',N'EL PEÑOL',N'Municipio'),
	 (N'52',N'52256',N'NARIÑO',N'EL ROSARIO',N'Municipio'),
	 (N'52',N'52258',N'NARIÑO',N'EL TABLÓN DE GÓMEZ',N'Municipio'),
	 (N'52',N'52260',N'NARIÑO',N'EL TAMBO',N'Municipio'),
	 (N'52',N'52287',N'NARIÑO',N'FUNES',N'Municipio'),
	 (N'52',N'52317',N'NARIÑO',N'GUACHUCAL',N'Municipio'),
	 (N'52',N'52320',N'NARIÑO',N'GUAITARILLA',N'Municipio'),
	 (N'52',N'52323',N'NARIÑO',N'GUALMATÁN',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'52',N'52352',N'NARIÑO',N'ILES',N'Municipio'),
	 (N'52',N'52354',N'NARIÑO',N'IMUÉS',N'Municipio'),
	 (N'52',N'52356',N'NARIÑO',N'IPIALES',N'Municipio'),
	 (N'52',N'52378',N'NARIÑO',N'LA CRUZ',N'Municipio'),
	 (N'52',N'52381',N'NARIÑO',N'LA FLORIDA',N'Municipio'),
	 (N'52',N'52385',N'NARIÑO',N'LA LLANADA',N'Municipio'),
	 (N'52',N'52390',N'NARIÑO',N'LA TOLA',N'Municipio'),
	 (N'52',N'52399',N'NARIÑO',N'LA UNIÓN',N'Municipio'),
	 (N'52',N'52405',N'NARIÑO',N'LEIVA',N'Municipio'),
	 (N'52',N'52411',N'NARIÑO',N'LINARES',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'52',N'52418',N'NARIÑO',N'LOS ANDES',N'Municipio'),
	 (N'52',N'52427',N'NARIÑO',N'MAGÜÍ',N'Municipio'),
	 (N'52',N'52435',N'NARIÑO',N'MALLAMA',N'Municipio'),
	 (N'52',N'52473',N'NARIÑO',N'MOSQUERA',N'Municipio'),
	 (N'52',N'52480',N'NARIÑO',N'NARIÑO',N'Municipio'),
	 (N'52',N'52490',N'NARIÑO',N'OLAYA HERRERA',N'Municipio'),
	 (N'52',N'52506',N'NARIÑO',N'OSPINA',N'Municipio'),
	 (N'52',N'52520',N'NARIÑO',N'FRANCISCO PIZARRO',N'Municipio'),
	 (N'52',N'52540',N'NARIÑO',N'POLICARPA',N'Municipio'),
	 (N'52',N'52560',N'NARIÑO',N'POTOSÍ',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'52',N'52565',N'NARIÑO',N'PROVIDENCIA',N'Municipio'),
	 (N'52',N'52573',N'NARIÑO',N'PUERRES',N'Municipio'),
	 (N'52',N'52585',N'NARIÑO',N'PUPIALES',N'Municipio'),
	 (N'52',N'52612',N'NARIÑO',N'RICAURTE',N'Municipio'),
	 (N'52',N'52621',N'NARIÑO',N'ROBERTO PAYÁN',N'Municipio'),
	 (N'52',N'52678',N'NARIÑO',N'SAMANIEGO',N'Municipio'),
	 (N'52',N'52683',N'NARIÑO',N'SANDONÁ',N'Municipio'),
	 (N'52',N'52685',N'NARIÑO',N'SAN BERNARDO',N'Municipio'),
	 (N'52',N'52687',N'NARIÑO',N'SAN LORENZO',N'Municipio'),
	 (N'52',N'52693',N'NARIÑO',N'SAN PABLO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'52',N'52694',N'NARIÑO',N'SAN PEDRO DE CARTAGO',N'Municipio'),
	 (N'52',N'52696',N'NARIÑO',N'SANTA BÁRBARA',N'Municipio'),
	 (N'52',N'52699',N'NARIÑO',N'SANTACRUZ',N'Municipio'),
	 (N'52',N'52720',N'NARIÑO',N'SAPUYES',N'Municipio'),
	 (N'52',N'52786',N'NARIÑO',N'TAMINANGO',N'Municipio'),
	 (N'52',N'52788',N'NARIÑO',N'TANGUA',N'Municipio'),
	 (N'52',N'52835',N'NARIÑO',N'SAN ANDRÉS DE TUMACO',N'Municipio'),
	 (N'52',N'52838',N'NARIÑO',N'TÚQUERRES',N'Municipio'),
	 (N'52',N'52885',N'NARIÑO',N'YACUANQUER',N'Municipio'),
	 (N'54',N'54001',N'NORTE DE SANTANDER',N'SAN JOSÉ DE CÚCUTA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'54',N'54003',N'NORTE DE SANTANDER',N'ÁBREGO',N'Municipio'),
	 (N'54',N'54051',N'NORTE DE SANTANDER',N'ARBOLEDAS',N'Municipio'),
	 (N'54',N'54099',N'NORTE DE SANTANDER',N'BOCHALEMA',N'Municipio'),
	 (N'54',N'54109',N'NORTE DE SANTANDER',N'BUCARASICA',N'Municipio'),
	 (N'54',N'54125',N'NORTE DE SANTANDER',N'CÁCOTA',N'Municipio'),
	 (N'54',N'54128',N'NORTE DE SANTANDER',N'CÁCHIRA',N'Municipio'),
	 (N'54',N'54172',N'NORTE DE SANTANDER',N'CHINÁCOTA',N'Municipio'),
	 (N'54',N'54174',N'NORTE DE SANTANDER',N'CHITAGÁ',N'Municipio'),
	 (N'54',N'54206',N'NORTE DE SANTANDER',N'CONVENCIÓN',N'Municipio'),
	 (N'54',N'54223',N'NORTE DE SANTANDER',N'CUCUTILLA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'54',N'54239',N'NORTE DE SANTANDER',N'DURANIA',N'Municipio'),
	 (N'54',N'54245',N'NORTE DE SANTANDER',N'EL CARMEN',N'Municipio'),
	 (N'54',N'54250',N'NORTE DE SANTANDER',N'EL TARRA',N'Municipio'),
	 (N'54',N'54261',N'NORTE DE SANTANDER',N'EL ZULIA',N'Municipio'),
	 (N'54',N'54313',N'NORTE DE SANTANDER',N'GRAMALOTE',N'Municipio'),
	 (N'54',N'54344',N'NORTE DE SANTANDER',N'HACARÍ',N'Municipio'),
	 (N'54',N'54347',N'NORTE DE SANTANDER',N'HERRÁN',N'Municipio'),
	 (N'54',N'54377',N'NORTE DE SANTANDER',N'LABATECA',N'Municipio'),
	 (N'54',N'54385',N'NORTE DE SANTANDER',N'LA ESPERANZA',N'Municipio'),
	 (N'54',N'54398',N'NORTE DE SANTANDER',N'LA PLAYA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'54',N'54405',N'NORTE DE SANTANDER',N'LOS PATIOS',N'Municipio'),
	 (N'54',N'54418',N'NORTE DE SANTANDER',N'LOURDES',N'Municipio'),
	 (N'54',N'54480',N'NORTE DE SANTANDER',N'MUTISCUA',N'Municipio'),
	 (N'54',N'54498',N'NORTE DE SANTANDER',N'OCAÑA',N'Municipio'),
	 (N'54',N'54518',N'NORTE DE SANTANDER',N'PAMPLONA',N'Municipio'),
	 (N'54',N'54520',N'NORTE DE SANTANDER',N'PAMPLONITA',N'Municipio'),
	 (N'54',N'54553',N'NORTE DE SANTANDER',N'PUERTO SANTANDER',N'Municipio'),
	 (N'54',N'54599',N'NORTE DE SANTANDER',N'RAGONVALIA',N'Municipio'),
	 (N'54',N'54660',N'NORTE DE SANTANDER',N'SALAZAR',N'Municipio'),
	 (N'54',N'54670',N'NORTE DE SANTANDER',N'SAN CALIXTO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'54',N'54673',N'NORTE DE SANTANDER',N'SAN CAYETANO',N'Municipio'),
	 (N'54',N'54680',N'NORTE DE SANTANDER',N'SANTIAGO',N'Municipio'),
	 (N'54',N'54720',N'NORTE DE SANTANDER',N'SARDINATA',N'Municipio'),
	 (N'54',N'54743',N'NORTE DE SANTANDER',N'SILOS',N'Municipio'),
	 (N'54',N'54800',N'NORTE DE SANTANDER',N'TEORAMA',N'Municipio'),
	 (N'54',N'54810',N'NORTE DE SANTANDER',N'TIBÚ',N'Municipio'),
	 (N'54',N'54820',N'NORTE DE SANTANDER',N'TOLEDO',N'Municipio'),
	 (N'54',N'54871',N'NORTE DE SANTANDER',N'VILLA CARO',N'Municipio'),
	 (N'54',N'54874',N'NORTE DE SANTANDER',N'VILLA DEL ROSARIO',N'Municipio'),
	 (N'63',N'63001',N'QUINDÍO',N'ARMENIA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'63',N'63111',N'QUINDÍO',N'BUENAVISTA',N'Municipio'),
	 (N'63',N'63130',N'QUINDÍO',N'CALARCÁ',N'Municipio'),
	 (N'63',N'63190',N'QUINDÍO',N'CIRCASIA',N'Municipio'),
	 (N'63',N'63212',N'QUINDÍO',N'CÓRDOBA',N'Municipio'),
	 (N'63',N'63272',N'QUINDÍO',N'FILANDIA',N'Municipio'),
	 (N'63',N'63302',N'QUINDÍO',N'GÉNOVA',N'Municipio'),
	 (N'63',N'63401',N'QUINDÍO',N'LA TEBAIDA',N'Municipio'),
	 (N'63',N'63470',N'QUINDÍO',N'MONTENEGRO',N'Municipio'),
	 (N'63',N'63548',N'QUINDÍO',N'PIJAO',N'Municipio'),
	 (N'63',N'63594',N'QUINDÍO',N'QUIMBAYA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'63',N'63690',N'QUINDÍO',N'SALENTO',N'Municipio'),
	 (N'66',N'66001',N'RISARALDA',N'PEREIRA',N'Municipio'),
	 (N'66',N'66045',N'RISARALDA',N'APÍA',N'Municipio'),
	 (N'66',N'66075',N'RISARALDA',N'BALBOA',N'Municipio'),
	 (N'66',N'66088',N'RISARALDA',N'BELÉN DE UMBRÍA',N'Municipio'),
	 (N'66',N'66170',N'RISARALDA',N'DOSQUEBRADAS',N'Municipio'),
	 (N'66',N'66318',N'RISARALDA',N'GUÁTICA',N'Municipio'),
	 (N'66',N'66383',N'RISARALDA',N'LA CELIA',N'Municipio'),
	 (N'66',N'66400',N'RISARALDA',N'LA VIRGINIA',N'Municipio'),
	 (N'66',N'66440',N'RISARALDA',N'MARSELLA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'66',N'66456',N'RISARALDA',N'MISTRATÓ',N'Municipio'),
	 (N'66',N'66572',N'RISARALDA',N'PUEBLO RICO',N'Municipio'),
	 (N'66',N'66594',N'RISARALDA',N'QUINCHÍA',N'Municipio'),
	 (N'66',N'66682',N'RISARALDA',N'SANTA ROSA DE CABAL',N'Municipio'),
	 (N'66',N'66687',N'RISARALDA',N'SANTUARIO',N'Municipio'),
	 (N'68',N'68001',N'SANTANDER',N'BUCARAMANGA',N'Municipio'),
	 (N'68',N'68013',N'SANTANDER',N'AGUADA',N'Municipio'),
	 (N'68',N'68020',N'SANTANDER',N'ALBANIA',N'Municipio'),
	 (N'68',N'68051',N'SANTANDER',N'ARATOCA',N'Municipio'),
	 (N'68',N'68077',N'SANTANDER',N'BARBOSA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'68',N'68079',N'SANTANDER',N'BARICHARA',N'Municipio'),
	 (N'68',N'68081',N'SANTANDER',N'BARRANCABERMEJA',N'Municipio'),
	 (N'68',N'68092',N'SANTANDER',N'BETULIA',N'Municipio'),
	 (N'68',N'68101',N'SANTANDER',N'BOLÍVAR',N'Municipio'),
	 (N'68',N'68121',N'SANTANDER',N'CABRERA',N'Municipio'),
	 (N'68',N'68132',N'SANTANDER',N'CALIFORNIA',N'Municipio'),
	 (N'68',N'68147',N'SANTANDER',N'CAPITANEJO',N'Municipio'),
	 (N'68',N'68152',N'SANTANDER',N'CARCASÍ',N'Municipio'),
	 (N'68',N'68160',N'SANTANDER',N'CEPITÁ',N'Municipio'),
	 (N'68',N'68162',N'SANTANDER',N'CERRITO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'68',N'68167',N'SANTANDER',N'CHARALÁ',N'Municipio'),
	 (N'68',N'68169',N'SANTANDER',N'CHARTA',N'Municipio'),
	 (N'68',N'68176',N'SANTANDER',N'CHIMA',N'Municipio'),
	 (N'68',N'68179',N'SANTANDER',N'CHIPATÁ',N'Municipio'),
	 (N'68',N'68190',N'SANTANDER',N'CIMITARRA',N'Municipio'),
	 (N'68',N'68207',N'SANTANDER',N'CONCEPCIÓN',N'Municipio'),
	 (N'68',N'68209',N'SANTANDER',N'CONFINES',N'Municipio'),
	 (N'68',N'68211',N'SANTANDER',N'CONTRATACIÓN',N'Municipio'),
	 (N'68',N'68217',N'SANTANDER',N'COROMORO',N'Municipio'),
	 (N'68',N'68229',N'SANTANDER',N'CURITÍ',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'68',N'68235',N'SANTANDER',N'EL CARMEN DE CHUCURI',N'Municipio'),
	 (N'68',N'68245',N'SANTANDER',N'EL GUACAMAYO',N'Municipio'),
	 (N'68',N'68250',N'SANTANDER',N'EL PEÑÓN',N'Municipio'),
	 (N'68',N'68255',N'SANTANDER',N'EL PLAYÓN',N'Municipio'),
	 (N'68',N'68264',N'SANTANDER',N'ENCINO',N'Municipio'),
	 (N'68',N'68266',N'SANTANDER',N'ENCISO',N'Municipio'),
	 (N'68',N'68271',N'SANTANDER',N'FLORIÁN',N'Municipio'),
	 (N'68',N'68276',N'SANTANDER',N'FLORIDABLANCA',N'Municipio'),
	 (N'68',N'68296',N'SANTANDER',N'GALÁN',N'Municipio'),
	 (N'68',N'68298',N'SANTANDER',N'GÁMBITA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'68',N'68307',N'SANTANDER',N'GIRÓN',N'Municipio'),
	 (N'68',N'68318',N'SANTANDER',N'GUACA',N'Municipio'),
	 (N'68',N'68320',N'SANTANDER',N'GUADALUPE',N'Municipio'),
	 (N'68',N'68322',N'SANTANDER',N'GUAPOTÁ',N'Municipio'),
	 (N'68',N'68324',N'SANTANDER',N'GUAVATÁ',N'Municipio'),
	 (N'68',N'68327',N'SANTANDER',N'GÜEPSA',N'Municipio'),
	 (N'68',N'68344',N'SANTANDER',N'HATO',N'Municipio'),
	 (N'68',N'68368',N'SANTANDER',N'JESÚS MARÍA',N'Municipio'),
	 (N'68',N'68370',N'SANTANDER',N'JORDÁN',N'Municipio'),
	 (N'68',N'68377',N'SANTANDER',N'LA BELLEZA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'68',N'68385',N'SANTANDER',N'LANDÁZURI',N'Municipio'),
	 (N'68',N'68397',N'SANTANDER',N'LA PAZ',N'Municipio'),
	 (N'68',N'68406',N'SANTANDER',N'LEBRIJA',N'Municipio'),
	 (N'68',N'68418',N'SANTANDER',N'LOS SANTOS',N'Municipio'),
	 (N'68',N'68425',N'SANTANDER',N'MACARAVITA',N'Municipio'),
	 (N'68',N'68432',N'SANTANDER',N'MÁLAGA',N'Municipio'),
	 (N'68',N'68444',N'SANTANDER',N'MATANZA',N'Municipio'),
	 (N'68',N'68464',N'SANTANDER',N'MOGOTES',N'Municipio'),
	 (N'68',N'68468',N'SANTANDER',N'MOLAGAVITA',N'Municipio'),
	 (N'68',N'68498',N'SANTANDER',N'OCAMONTE',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'68',N'68500',N'SANTANDER',N'OIBA',N'Municipio'),
	 (N'68',N'68502',N'SANTANDER',N'ONZAGA',N'Municipio'),
	 (N'68',N'68522',N'SANTANDER',N'PALMAR',N'Municipio'),
	 (N'68',N'68524',N'SANTANDER',N'PALMAS DEL SOCORRO',N'Municipio'),
	 (N'68',N'68533',N'SANTANDER',N'PÁRAMO',N'Municipio'),
	 (N'68',N'68547',N'SANTANDER',N'PIEDECUESTA',N'Municipio'),
	 (N'68',N'68549',N'SANTANDER',N'PINCHOTE',N'Municipio'),
	 (N'68',N'68572',N'SANTANDER',N'PUENTE NACIONAL',N'Municipio'),
	 (N'68',N'68573',N'SANTANDER',N'PUERTO PARRA',N'Municipio'),
	 (N'68',N'68575',N'SANTANDER',N'PUERTO WILCHES',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'68',N'68615',N'SANTANDER',N'RIONEGRO',N'Municipio'),
	 (N'68',N'68655',N'SANTANDER',N'SABANA DE TORRES',N'Municipio'),
	 (N'68',N'68669',N'SANTANDER',N'SAN ANDRÉS',N'Municipio'),
	 (N'68',N'68673',N'SANTANDER',N'SAN BENITO',N'Municipio'),
	 (N'68',N'68679',N'SANTANDER',N'SAN GIL',N'Municipio'),
	 (N'68',N'68682',N'SANTANDER',N'SAN JOAQUÍN',N'Municipio'),
	 (N'68',N'68684',N'SANTANDER',N'SAN JOSÉ DE MIRANDA',N'Municipio'),
	 (N'68',N'68686',N'SANTANDER',N'SAN MIGUEL',N'Municipio'),
	 (N'68',N'68689',N'SANTANDER',N'SAN VICENTE DE CHUCURÍ',N'Municipio'),
	 (N'68',N'68705',N'SANTANDER',N'SANTA BÁRBARA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'68',N'68720',N'SANTANDER',N'SANTA HELENA DEL OPÓN',N'Municipio'),
	 (N'68',N'68745',N'SANTANDER',N'SIMACOTA',N'Municipio'),
	 (N'68',N'68755',N'SANTANDER',N'SOCORRO',N'Municipio'),
	 (N'68',N'68770',N'SANTANDER',N'SUAITA',N'Municipio'),
	 (N'68',N'68773',N'SANTANDER',N'SUCRE',N'Municipio'),
	 (N'68',N'68780',N'SANTANDER',N'SURATÁ',N'Municipio'),
	 (N'68',N'68820',N'SANTANDER',N'TONA',N'Municipio'),
	 (N'68',N'68855',N'SANTANDER',N'VALLE DE SAN JOSÉ',N'Municipio'),
	 (N'68',N'68861',N'SANTANDER',N'VÉLEZ',N'Municipio'),
	 (N'68',N'68867',N'SANTANDER',N'VETAS',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'68',N'68872',N'SANTANDER',N'VILLANUEVA',N'Municipio'),
	 (N'68',N'68895',N'SANTANDER',N'ZAPATOCA',N'Municipio'),
	 (N'70',N'70001',N'SUCRE',N'SINCELEJO',N'Municipio'),
	 (N'70',N'70110',N'SUCRE',N'BUENAVISTA',N'Municipio'),
	 (N'70',N'70124',N'SUCRE',N'CAIMITO',N'Municipio'),
	 (N'70',N'70204',N'SUCRE',N'COLOSÓ',N'Municipio'),
	 (N'70',N'70215',N'SUCRE',N'COROZAL',N'Municipio'),
	 (N'70',N'70221',N'SUCRE',N'COVEÑAS',N'Municipio'),
	 (N'70',N'70230',N'SUCRE',N'CHALÁN',N'Municipio'),
	 (N'70',N'70233',N'SUCRE',N'EL ROBLE',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'70',N'70235',N'SUCRE',N'GALERAS',N'Municipio'),
	 (N'70',N'70265',N'SUCRE',N'GUARANDA',N'Municipio'),
	 (N'70',N'70400',N'SUCRE',N'LA UNIÓN',N'Municipio'),
	 (N'70',N'70418',N'SUCRE',N'LOS PALMITOS',N'Municipio'),
	 (N'70',N'70429',N'SUCRE',N'MAJAGUAL',N'Municipio'),
	 (N'70',N'70473',N'SUCRE',N'MORROA',N'Municipio'),
	 (N'70',N'70508',N'SUCRE',N'OVEJAS',N'Municipio'),
	 (N'70',N'70523',N'SUCRE',N'PALMITO',N'Municipio'),
	 (N'70',N'70670',N'SUCRE',N'SAMPUÉS',N'Municipio'),
	 (N'70',N'70678',N'SUCRE',N'SAN BENITO ABAD',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'70',N'70702',N'SUCRE',N'SAN JUAN DE BETULIA',N'Municipio'),
	 (N'70',N'70708',N'SUCRE',N'SAN MARCOS',N'Municipio'),
	 (N'70',N'70713',N'SUCRE',N'SAN ONOFRE',N'Municipio'),
	 (N'70',N'70717',N'SUCRE',N'SAN PEDRO',N'Municipio'),
	 (N'70',N'70742',N'SUCRE',N'SAN LUIS DE SINCÉ',N'Municipio'),
	 (N'70',N'70771',N'SUCRE',N'SUCRE',N'Municipio'),
	 (N'70',N'70820',N'SUCRE',N'SANTIAGO DE TOLÚ',N'Municipio'),
	 (N'70',N'70823',N'SUCRE',N'SAN JOSÉ DE TOLUVIEJO',N'Municipio'),
	 (N'73',N'73001',N'TOLIMA',N'IBAGUÉ',N'Municipio'),
	 (N'73',N'73024',N'TOLIMA',N'ALPUJARRA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'73',N'73026',N'TOLIMA',N'ALVARADO',N'Municipio'),
	 (N'73',N'73030',N'TOLIMA',N'AMBALEMA',N'Municipio'),
	 (N'73',N'73043',N'TOLIMA',N'ANZOÁTEGUI',N'Municipio'),
	 (N'73',N'73055',N'TOLIMA',N'ARMERO',N'Municipio'),
	 (N'73',N'73067',N'TOLIMA',N'ATACO',N'Municipio'),
	 (N'73',N'73124',N'TOLIMA',N'CAJAMARCA',N'Municipio'),
	 (N'73',N'73148',N'TOLIMA',N'CARMEN DE APICALÁ',N'Municipio'),
	 (N'73',N'73152',N'TOLIMA',N'CASABIANCA',N'Municipio'),
	 (N'73',N'73168',N'TOLIMA',N'CHAPARRAL',N'Municipio'),
	 (N'73',N'73200',N'TOLIMA',N'COELLO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'73',N'73217',N'TOLIMA',N'COYAIMA',N'Municipio'),
	 (N'73',N'73226',N'TOLIMA',N'CUNDAY',N'Municipio'),
	 (N'73',N'73236',N'TOLIMA',N'DOLORES',N'Municipio'),
	 (N'73',N'73268',N'TOLIMA',N'ESPINAL',N'Municipio'),
	 (N'73',N'73270',N'TOLIMA',N'FALAN',N'Municipio'),
	 (N'73',N'73275',N'TOLIMA',N'FLANDES',N'Municipio'),
	 (N'73',N'73283',N'TOLIMA',N'FRESNO',N'Municipio'),
	 (N'73',N'73319',N'TOLIMA',N'GUAMO',N'Municipio'),
	 (N'73',N'73347',N'TOLIMA',N'HERVEO',N'Municipio'),
	 (N'73',N'73349',N'TOLIMA',N'HONDA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'73',N'73352',N'TOLIMA',N'ICONONZO',N'Municipio'),
	 (N'73',N'73408',N'TOLIMA',N'LÉRIDA',N'Municipio'),
	 (N'73',N'73411',N'TOLIMA',N'LÍBANO',N'Municipio'),
	 (N'73',N'73443',N'TOLIMA',N'SAN SEBASTIÁN DE MARIQUITA',N'Municipio'),
	 (N'73',N'73449',N'TOLIMA',N'MELGAR',N'Municipio'),
	 (N'73',N'73461',N'TOLIMA',N'MURILLO',N'Municipio'),
	 (N'73',N'73483',N'TOLIMA',N'NATAGAIMA',N'Municipio'),
	 (N'73',N'73504',N'TOLIMA',N'ORTEGA',N'Municipio'),
	 (N'73',N'73520',N'TOLIMA',N'PALOCABILDO',N'Municipio'),
	 (N'73',N'73547',N'TOLIMA',N'PIEDRAS',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'73',N'73555',N'TOLIMA',N'PLANADAS',N'Municipio'),
	 (N'73',N'73563',N'TOLIMA',N'PRADO',N'Municipio'),
	 (N'73',N'73585',N'TOLIMA',N'PURIFICACIÓN',N'Municipio'),
	 (N'73',N'73616',N'TOLIMA',N'RIOBLANCO',N'Municipio'),
	 (N'73',N'73622',N'TOLIMA',N'RONCESVALLES',N'Municipio'),
	 (N'73',N'73624',N'TOLIMA',N'ROVIRA',N'Municipio'),
	 (N'73',N'73671',N'TOLIMA',N'SALDAÑA',N'Municipio'),
	 (N'73',N'73675',N'TOLIMA',N'SAN ANTONIO',N'Municipio'),
	 (N'73',N'73678',N'TOLIMA',N'SAN LUIS',N'Municipio'),
	 (N'73',N'73686',N'TOLIMA',N'SANTA ISABEL',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'73',N'73770',N'TOLIMA',N'SUÁREZ',N'Municipio'),
	 (N'73',N'73854',N'TOLIMA',N'VALLE DE SAN JUAN',N'Municipio'),
	 (N'73',N'73861',N'TOLIMA',N'VENADILLO',N'Municipio'),
	 (N'73',N'73870',N'TOLIMA',N'VILLAHERMOSA',N'Municipio'),
	 (N'73',N'73873',N'TOLIMA',N'VILLARRICA',N'Municipio'),
	 (N'76',N'76001',N'VALLE DEL CAUCA',N'CALI',N'Municipio'),
	 (N'76',N'76020',N'VALLE DEL CAUCA',N'ALCALÁ',N'Municipio'),
	 (N'76',N'76036',N'VALLE DEL CAUCA',N'ANDALUCÍA',N'Municipio'),
	 (N'76',N'76041',N'VALLE DEL CAUCA',N'ANSERMANUEVO',N'Municipio'),
	 (N'76',N'76054',N'VALLE DEL CAUCA',N'ARGELIA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'76',N'76100',N'VALLE DEL CAUCA',N'BOLÍVAR',N'Municipio'),
	 (N'76',N'76109',N'VALLE DEL CAUCA',N'BUENAVENTURA',N'Municipio'),
	 (N'76',N'76111',N'VALLE DEL CAUCA',N'GUADALAJARA DE BUGA',N'Municipio'),
	 (N'76',N'76113',N'VALLE DEL CAUCA',N'BUGALAGRANDE',N'Municipio'),
	 (N'76',N'76122',N'VALLE DEL CAUCA',N'CAICEDONIA',N'Municipio'),
	 (N'76',N'76126',N'VALLE DEL CAUCA',N'CALIMA',N'Municipio'),
	 (N'76',N'76130',N'VALLE DEL CAUCA',N'CANDELARIA',N'Municipio'),
	 (N'76',N'76147',N'VALLE DEL CAUCA',N'CARTAGO',N'Municipio'),
	 (N'76',N'76233',N'VALLE DEL CAUCA',N'DAGUA',N'Municipio'),
	 (N'76',N'76243',N'VALLE DEL CAUCA',N'EL ÁGUILA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'76',N'76246',N'VALLE DEL CAUCA',N'EL CAIRO',N'Municipio'),
	 (N'76',N'76248',N'VALLE DEL CAUCA',N'EL CERRITO',N'Municipio'),
	 (N'76',N'76250',N'VALLE DEL CAUCA',N'EL DOVIO',N'Municipio'),
	 (N'76',N'76275',N'VALLE DEL CAUCA',N'FLORIDA',N'Municipio'),
	 (N'76',N'76306',N'VALLE DEL CAUCA',N'GINEBRA',N'Municipio'),
	 (N'76',N'76318',N'VALLE DEL CAUCA',N'GUACARÍ',N'Municipio'),
	 (N'76',N'76364',N'VALLE DEL CAUCA',N'JAMUNDÍ',N'Municipio'),
	 (N'76',N'76377',N'VALLE DEL CAUCA',N'LA CUMBRE',N'Municipio'),
	 (N'76',N'76400',N'VALLE DEL CAUCA',N'LA UNIÓN',N'Municipio'),
	 (N'76',N'76403',N'VALLE DEL CAUCA',N'LA VICTORIA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'76',N'76497',N'VALLE DEL CAUCA',N'OBANDO',N'Municipio'),
	 (N'76',N'76520',N'VALLE DEL CAUCA',N'PALMIRA',N'Municipio'),
	 (N'76',N'76563',N'VALLE DEL CAUCA',N'PRADERA',N'Municipio'),
	 (N'76',N'76606',N'VALLE DEL CAUCA',N'RESTREPO',N'Municipio'),
	 (N'76',N'76616',N'VALLE DEL CAUCA',N'RIOFRÍO',N'Municipio'),
	 (N'76',N'76622',N'VALLE DEL CAUCA',N'ROLDANILLO',N'Municipio'),
	 (N'76',N'76670',N'VALLE DEL CAUCA',N'SAN PEDRO',N'Municipio'),
	 (N'76',N'76736',N'VALLE DEL CAUCA',N'SEVILLA',N'Municipio'),
	 (N'76',N'76823',N'VALLE DEL CAUCA',N'TORO',N'Municipio'),
	 (N'76',N'76828',N'VALLE DEL CAUCA',N'TRUJILLO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'76',N'76834',N'VALLE DEL CAUCA',N'TULUÁ',N'Municipio'),
	 (N'76',N'76845',N'VALLE DEL CAUCA',N'ULLOA',N'Municipio'),
	 (N'76',N'76863',N'VALLE DEL CAUCA',N'VERSALLES',N'Municipio'),
	 (N'76',N'76869',N'VALLE DEL CAUCA',N'VIJES',N'Municipio'),
	 (N'76',N'76890',N'VALLE DEL CAUCA',N'YOTOCO',N'Municipio'),
	 (N'76',N'76892',N'VALLE DEL CAUCA',N'YUMBO',N'Municipio'),
	 (N'76',N'76895',N'VALLE DEL CAUCA',N'ZARZAL',N'Municipio'),
	 (N'81',N'81001',N'ARAUCA',N'ARAUCA',N'Municipio'),
	 (N'81',N'81065',N'ARAUCA',N'ARAUQUITA',N'Municipio'),
	 (N'81',N'81220',N'ARAUCA',N'CRAVO NORTE',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'81',N'81300',N'ARAUCA',N'FORTUL',N'Municipio'),
	 (N'81',N'81591',N'ARAUCA',N'PUERTO RONDÓN',N'Municipio'),
	 (N'81',N'81736',N'ARAUCA',N'SARAVENA',N'Municipio'),
	 (N'81',N'81794',N'ARAUCA',N'TAME',N'Municipio'),
	 (N'85',N'85001',N'CASANARE',N'YOPAL',N'Municipio'),
	 (N'85',N'85010',N'CASANARE',N'AGUAZUL',N'Municipio'),
	 (N'85',N'85015',N'CASANARE',N'CHÁMEZA',N'Municipio'),
	 (N'85',N'85125',N'CASANARE',N'HATO COROZAL',N'Municipio'),
	 (N'85',N'85136',N'CASANARE',N'LA SALINA',N'Municipio'),
	 (N'85',N'85139',N'CASANARE',N'MANÍ',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'85',N'85162',N'CASANARE',N'MONTERREY',N'Municipio'),
	 (N'85',N'85225',N'CASANARE',N'NUNCHÍA',N'Municipio'),
	 (N'85',N'85230',N'CASANARE',N'OROCUÉ',N'Municipio'),
	 (N'85',N'85250',N'CASANARE',N'PAZ DE ARIPORO',N'Municipio'),
	 (N'85',N'85263',N'CASANARE',N'PORE',N'Municipio'),
	 (N'85',N'85279',N'CASANARE',N'RECETOR',N'Municipio'),
	 (N'85',N'85300',N'CASANARE',N'SABANALARGA',N'Municipio'),
	 (N'85',N'85315',N'CASANARE',N'SÁCAMA',N'Municipio'),
	 (N'85',N'85325',N'CASANARE',N'SAN LUIS DE PALENQUE',N'Municipio'),
	 (N'85',N'85400',N'CASANARE',N'TÁMARA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'85',N'85410',N'CASANARE',N'TAURAMENA',N'Municipio'),
	 (N'85',N'85430',N'CASANARE',N'TRINIDAD',N'Municipio'),
	 (N'85',N'85440',N'CASANARE',N'VILLANUEVA',N'Municipio'),
	 (N'86',N'86001',N'PUTUMAYO',N'MOCOA',N'Municipio'),
	 (N'86',N'86219',N'PUTUMAYO',N'COLÓN',N'Municipio'),
	 (N'86',N'86320',N'PUTUMAYO',N'ORITO',N'Municipio'),
	 (N'86',N'86568',N'PUTUMAYO',N'PUERTO ASÍS',N'Municipio'),
	 (N'86',N'86569',N'PUTUMAYO',N'PUERTO CAICEDO',N'Municipio'),
	 (N'86',N'86571',N'PUTUMAYO',N'PUERTO GUZMÁN',N'Municipio'),
	 (N'86',N'86573',N'PUTUMAYO',N'PUERTO LEGUÍZAMO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'86',N'86749',N'PUTUMAYO',N'SIBUNDOY',N'Municipio'),
	 (N'86',N'86755',N'PUTUMAYO',N'SAN FRANCISCO',N'Municipio'),
	 (N'86',N'86757',N'PUTUMAYO',N'SAN MIGUEL',N'Municipio'),
	 (N'86',N'86760',N'PUTUMAYO',N'SANTIAGO',N'Municipio'),
	 (N'86',N'86865',N'PUTUMAYO',N'VALLE DEL GUAMUEZ',N'Municipio'),
	 (N'86',N'86885',N'PUTUMAYO',N'VILLAGARZÓN',N'Municipio'),
	 (N'88',N'88001',N'ARCHIPIÉLAGO DE SAN ANDRÉS. PROVIDENCIA Y SANTA CATALINA',N'SAN ANDRÉS',N'Isla'),
	 (N'88',N'88564',N'ARCHIPIÉLAGO DE SAN ANDRÉS. PROVIDENCIA Y SANTA CATALINA',N'PROVIDENCIA',N'Municipio'),
	 (N'91',N'91001',N'AMAZONAS',N'LETICIA',N'Municipio'),
	 (N'91',N'91263',N'AMAZONAS',N'EL ENCANTO',N'Área no municipalizada');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'91',N'91405',N'AMAZONAS',N'LA CHORRERA',N'Área no municipalizada'),
	 (N'91',N'91407',N'AMAZONAS',N'LA PEDRERA',N'Área no municipalizada'),
	 (N'91',N'91430',N'AMAZONAS',N'LA VICTORIA',N'Área no municipalizada'),
	 (N'91',N'91460',N'AMAZONAS',N'MIRITÍ - PARANÁ',N'Área no municipalizada'),
	 (N'91',N'91530',N'AMAZONAS',N'PUERTO ALEGRÍA',N'Área no municipalizada'),
	 (N'91',N'91536',N'AMAZONAS',N'PUERTO ARICA',N'Área no municipalizada'),
	 (N'91',N'91540',N'AMAZONAS',N'PUERTO NARIÑO',N'Municipio'),
	 (N'91',N'91669',N'AMAZONAS',N'PUERTO SANTANDER',N'Área no municipalizada'),
	 (N'91',N'91798',N'AMAZONAS',N'TARAPACÁ',N'Área no municipalizada'),
	 (N'94',N'94001',N'GUAINÍA',N'INÍRIDA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'94',N'94343',N'GUAINÍA',N'BARRANCOMINAS',N'Municipio'),
	 (N'94',N'94883',N'GUAINÍA',N'SAN FELIPE',N'Área no municipalizada'),
	 (N'94',N'94884',N'GUAINÍA',N'PUERTO COLOMBIA',N'Área no municipalizada'),
	 (N'94',N'94885',N'GUAINÍA',N'LA GUADALUPE',N'Área no municipalizada'),
	 (N'94',N'94886',N'GUAINÍA',N'CACAHUAL',N'Área no municipalizada'),
	 (N'94',N'94887',N'GUAINÍA',N'PANA PANA',N'Área no municipalizada'),
	 (N'94',N'94888',N'GUAINÍA',N'MORICHAL',N'Área no municipalizada'),
	 (N'95',N'95001',N'GUAVIARE',N'SAN JOSÉ DEL GUAVIARE',N'Municipio'),
	 (N'95',N'95015',N'GUAVIARE',N'CALAMAR',N'Municipio'),
	 (N'95',N'95025',N'GUAVIARE',N'EL RETORNO',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'95',N'95200',N'GUAVIARE',N'MIRAFLORES',N'Municipio'),
	 (N'97',N'97001',N'VAUPÉS',N'MITÚ',N'Municipio'),
	 (N'97',N'97161',N'VAUPÉS',N'CARURÚ',N'Municipio'),
	 (N'97',N'97511',N'VAUPÉS',N'PACOA',N'Área no municipalizada'),
	 (N'97',N'97666',N'VAUPÉS',N'TARAIRA',N'Municipio'),
	 (N'97',N'97777',N'VAUPÉS',N'PAPUNAHUA',N'Área no municipalizada'),
	 (N'97',N'97889',N'VAUPÉS',N'YAVARATÉ',N'Área no municipalizada'),
	 (N'99',N'99001',N'VICHADA',N'PUERTO CARREÑO',N'Municipio'),
	 (N'99',N'99524',N'VICHADA',N'LA PRIMAVERA',N'Municipio'),
	 (N'99',N'99624',N'VICHADA',N'SANTA ROSALÍA',N'Municipio');
INSERT INTO MovilidadSource.dbo.[DIVIPOLA-_C_digos_municipios_20240706] (Codigo_Departamento,Codigo_Municipio,Nombre_Departamento,Nombre_Municipio,Tipo_Municipio_Isla_Area_no_municipalizada) VALUES
	 (N'99',N'99773',N'VICHADA',N'CUMARIBO',N'Municipio'),
	 (N'Fuente: DANE.',NULL,NULL,NULL,NULL),
	 (N'Nota: En la actualidad el país se compone de 1.102 municipios. 18 Áreas no municipalizadas y la Isla de San Andrés.',NULL,NULL,NULL,NULL),
	 (N'Actualizado al: 10 de Junio de 2020',NULL,NULL,NULL,NULL),
	 (N'*Desde el 1 de diciembre de 2019 comenzó a regir la Ordenanza 248 de 2019 de la Asamblea Departamental de Guainía que crea el municipio de Barrancominas.',NULL,NULL,NULL,NULL),
	 (N'conformado por las áreas no municipalizadas de Barrancominas y Mapiripana. Se incorporó en la DIVIPOLA en Mayo de 2020 una vez definida la información geográfica por el IGAC.',NULL,NULL,NULL,NULL);
